cluster: unfunded
project: unfunded

accountNumber: "662843554732"

calico:
  enabled: true
  targetRevision: v3.30.0
  configuration:
    enabled: false

coreDNS:
  enabled: true
  targetRevision: v1.36.2
  configuration:
    enabled: false

grafana-alloy:
  enabled: true
  targetRevision: 0.4.0
  configuration:
    enabled: false

karpenter:
  enabled: true
  targetRevision: v0.32.9
  configuration:
    enabled: true

karpenter-crds:
  amiSelectorName: "1-31-EKS-FIPS*"
  enabled: true
  selectorTag: unfunded
  migration: true

vpc-cni:
  enabled: true
  targetRevision: v1.19.0
  configuration:
    enabled: false
