cluster: unfunded
project: unfunded

calico:
  enabled: true
  targetRevision: v3.27.0
  configuration:
    enabled: false

coreDNS:
  enabled: true
  targetRevision: v1.29.0
  configuration:
    enabled: false

grafana-alloy:
  enabled: true
  targetRevision: 0.4.0
  configuration:
    enabled: false

karpenter:
  enabled: true
  targetRevision: 1.0.8
  configuration:
    enabled: true

karpenter-crds:
  amiSelectorName: "1-31-EKS-FIPS*"
  enabled: true
  selectorTag: unfunded
  migration: true

vpc-cni:
  enabled: true
  targetRevision: v1.16.2
  configuration:
    enabled: false
