environment: unfunded

gitRevision: feat/flexible-gitops

configuration:
  configurationRepo: https://github.com/uc-cdis/gen3-gitops
  configurationRevision: feat/flexible-gitops

karpenter:
  enabled: true
  targetRevision: v0.32.9
  configuration:
    enabled: true

# No enabled flag, because we want this to come up with karpenter at all times
karpenter-templates:
  configuration:
    enabled: true
