cluster: unfunded

configuration:
  configurationRepo: https://github.com/uc-cdis/gen3-gitops
  configurationRevision: feat/flexible-gitops

calico:
  enabled: true
  targetRevision: v3.27.0
  configuration:
    enabled: false

coreDNS:
  enabled: true
  targetRevision: v1.29.0
  configuration:
    enabled: false

grafana-alloy:
  enabled: true
  targetRevision: 0.4.0
  configuration:
    enabled: false

karpenter:
  enabled: true
  targetRevision: v0.32.9
  configuration:
    enabled: true

# No enabled flag, because we want this to come up with karpenter at all times
karpenter-templates:
  configuration:
    enabled: true
  targetRevision: master

vpc-cni:
  enabled: true
  targetRevision: v1.16.2
  configuration:
    enabled: false
