cluster: unfunded
project: unfunded

configuration:
  configurationRevision: feat/karpenter-crds

calico:
  enabled: true
  targetRevision: v3.27.0
  configuration:
    enabled: false

coreDNS:
  enabled: true
  targetRevision: v1.29.0
  configuration:
    enabled: false

grafana-alloy:
  enabled: true
  targetRevision: 0.4.0
  configuration:
    enabled: false

karpenter:
  enabled: true
  targetRevision: v0.32.9
  configuration:
    enabled: true

karpenter-crds:
  enabled: true

vpc-cni:
  enabled: true
  targetRevision: v1.16.2
  configuration:
    enabled: false
