cluster: unfunded
project: unfunded

accountNumber: "662843554732"

alb-controller:
  enabled: true
  configuration:
    enabled: false

aws-s3-mountpoint:
  enabled: true
  configuration:
    enabled: false

calico:
  enabled: true
  configuration:
    enabled: false

coreDNS:
  enabled: true
  configuration:
    enabled: false

ebs-csi-driver:
  enabled: false
  configuration:
    enabled: false

fluentd:
  enabled: false
  configuration:
    enabled: false

grafana-alloy:
  enabled: true
  configuration:
    enabled: false

karpenter:
  enabled: true
  targetRevision: 1.0.8
  configuration:
    enabled: true

karpenter-crds:
  amiSelectorName: "1-31-EKS-FIPS*"
  enabled: true
  selectorTag: unfunded
  migration: true

kube-state-metrics:
  enabled: true
  configuration:
    enabled: false

vpc-cni:
  enabled: true
  configuration:
    enabled: false
