apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gen3-pdp-commons
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - path: helm/gen3
      repoURL: https://github.com/uc-cdis/gen3-helm
      targetRevision: master
      helm:
        releaseName: gen3-pdp-commons
        valueFiles:
          - $values/pdp-commons/mc2dp.data-commons.org/values/values.yaml
    - repoURL: 'https://github.com/uc-cdis/gen3-gitops.git'
      targetRevision: master
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        role: gen3
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
