apiVersion: v1
kind: ConfigMap
metadata:
  # This is a separate list of namespaces that can be scaled down, but will not be automatically scaled up every
  # morning. This is for things like rarely-used dev environments and the like
  name: spinup-blacklist
  namespace: default
data:
  blacklist: |
    jenkins*
