apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gen3-niaiddata
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - path: helm/gen3
      repoURL: https://github.com/uc-cdis/gen3-helm
      targetRevision: master
      helm:
        releaseName: niaiddata
        valueFiles:
          - $values/unfunded/diseasedatahub.org/values/values.yaml
          - $values/unfunded/diseasedatahub.org/values/fence.yaml
          - $values/unfunded/diseasedatahub.org/values/portal.yaml
          - $values/unfunded/diseasedatahub.org/values/guppy.yaml
          - $values/unfunded/diseasedatahub.org/values/hatchery.yaml
          - $values/unfunded/diseasedatahub.org/values/etl.yaml
    - repoURL: 'https://github.com/uc-cdis/gen3-gitops.git'
      targetRevision: master
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: diseasedatahub
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
