apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vectis-search-auth-proxy
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: default
    kind: SecretStore
  target:
    name: vectis-search-auth-proxy
    creationPolicy: Owner
    template:
      data:
        postgres_dsn: postgresql://{{ .username }}:{{ .password }}@vectis-aurora-cluster-new.cluster-cm1siekw0ufl.us-east-1.rds.amazonaws.com:5432/postgres
  data:
    - secretKey: username
      remoteRef:
        key: vectis-search-user
        property: username
    - secretKey: password
      remoteRef:
        key: vectis-search-user
        property: password