cluster: kidsfirst-skfqa
project: kidsfirst

eksClusterName: skfqa

accountNumber: "222487244010"

eksClusterEndpoint: "https://62A6B511421C903352EFD814BE887885.sk1.us-east-1.eks.amazonaws.com"

alb-controller:
  enabled: true
  configuration:
    enabled: false

aws-s3-mountpoint:
  enabled: true
  configuration:
    enabled: false

calico:
  enabled: true
  configuration:
    enabled: false

coreDNS:
  enabled: true
  configuration:
    enabled: false

ebs-csi-driver:
  enabled: false
  configuration:
    enabled: false

external-secrets:
  enabled: true

fluentd:
  enabled: false
  configuration:
    enabled: false

kube-state-metrics:
  enabled: true
  configuration:
    enabled: false

grafana-alloy:
  enabled: true
  configuration:
    enabled: false

karpenter:
  enabled: true
  targetRevision: "1.0.8"

karpenter-crds:
  amiSelectorName: "1-31-EKS-FIPS*"
  enabled: true
  migration: true
  selectorTag: skfqa

vpc-cni:
  enabled: true
  configuration:
    enabled: false
