global:
  hostname: null
  dictionaryUrl: https://s3.amazonaws.com/dictionary-artifacts/anvil/master/schema.json
  pdb: true
  aws:
    externalSecrets:
      enabled: true
      externalSecretAwsCreds: ci-aws-config
    secretStoreServiceAccount:
      enabled: true
      name: secret-store-sa
      roleArn: arn:aws:iam::707767160287:role/devplanetv2-external-secrets-sa
    sower_role: sower-jobs-role
  externalSecrets:
    deploy: true
    dbCreate: true
  manifestGlobalExtraValues:
    fence_url: https://hostname/user
    google_enabled: true
  tierAccessLevel: libre
mutatingWebhook:
  enabled: false
postgresql:
  primary:
    persistence:
      enabled: true
      size: 1Gi
  image:
    registry: quay.io
    repository: cdis/postgresql
    tag: 14.5.0-debian-11-r35
hatchery:
  replicaCount: 2
  autoscaling:
    enabled: true
  image:
    tag: '2025.09'
  hatchery:
    containers:
      - target-port: 8888
        cpu-limit: '0.5'
        memory-limit: 1Gi
        name: (Tutorial) Bacpac Synthetic Data Analysis Notebook
        image: quay.io/cdis/heal-notebooks:bacpac__10670ad79b4488cfa9f1b3681ce52bc3f1139b5a
        env:
          FRAME_ANCESTORS: https://<hostname>
        args:
          - --NotebookApp.base_url=/lw-workspace/proxy/
          - --NotebookApp.password=''
          - --NotebookApp.token=''
          - --NotebookApp.quit_button=False
        command:
          - start-notebook.sh
        path-rewrite: /lw-workspace/proxy/
        use-tls: 'false'
        ready-probe: /lw-workspace/proxy/
        lifecycle-post-start:
          - /bin/sh
          - -c
          - export IAM=`whoami`; rm -rf /home/$IAM/pd/dockerHome; rm -rf /home/$IAM/pd/lost+found;
            ln -s /data /home/$IAM/pd/; true
        user-uid: 1000
        fs-gid: 100
indexd:
  replicaCount: 2
  autoscaling:
    enabled: true
  resources:
    requests:
      memory: 105Mi
      cpu: 15m
  defaultPrefix: ''
  enabled: true
  image:
    repository: quay.io/cdis/indexd
    tag: '2025.09'
  externalSecrets:
    createK8sServiceCredsSecret: true
  secrets:
    userdb:
      ssj: null
      gateway: null
metadata:
  replicaCount: 2
  autoscaling:
    enabled: true
  image:
    repository: quay.io/cdis/metadata-service
    tag: '2025.09'
  resources:
    requests:
      memory: 25Mi
  enabled: true
  externalSecrets:
    createK8sMetadataSecret: true
  useAggMds: 'True'
  aggMdsNamespace: default
  aggMdsConfig: "{\n  \"gen3_commons\": {\n    \"HEAL\": {\n      \"mds_url\": \"\
    http://revproxy-service\",\n      \"commons_url\": \"http://revproxy-service\"\
    \n    }\n  },\n  \"adapter_commons\": {}\n}\n"
maxUnavailable: ''
elasticsearch:
  maxUnavailable: ''
  volumeClaimTemplate:
    resources:
      requests:
        storage: 1Gi
sower:
  replicaCount: 2
  autoscaling:
    enabled: true
  image:
    repository: quay.io/cdis/sower
    tag: '2025.09'
  enabled: true
  serviceAccount:
    create: true
    name: sower-service-account
  externalSecrets:
    createK8sPelicanServiceSecret: false
    pelicanserviceG3auto: ci-pelicanservice-g3auto
    createK8sSowerJobsSecret: true
  sowerConfig:
    - name: pelican-export
      action: export
      container:
        name: job-task
        image: quay.io/cdis/pelican-export:2025.09
        pull_policy: Always
        env:
          - name: DICTIONARY_URL
            valueFrom:
              configMapKeyRef:
                name: manifest-global
                key: dictionary_url
          - name: GEN3_HOSTNAME
            valueFrom:
              configMapKeyRef:
                name: manifest-global
                key: hostname
          - name: ROOT_NODE
            value: subject
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: sheepdog-dbcreds
                key: host
          - name: DB_DATABASE
            valueFrom:
              secretKeyRef:
                name: sheepdog-dbcreds
                key: database
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: sheepdog-dbcreds
                key: username
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: sheepdog-dbcreds
                key: password
          - name: SHEEPDOG
            valueFrom:
              secretKeyRef:
                name: indexd-service-creds
                key: sheepdog
        volumeMounts:
          - name: pelican-creds-volume
            readOnly: true
            mountPath: /pelican-creds.json
            subPath: config.json
        cpu-limit: '0.5'
        memory-limit: 1Gi
      volumes:
        - name: pelican-creds-volume
          secret:
            secretName: pelicanservice-g3auto
      restart_policy: Never
    - name: pelican-export-files
      action: export-files
      container:
        name: job-task
        image: quay.io/cdis/pelican-export:2025.09
        pull_policy: Always
        env:
          - name: DICTIONARY_URL
            valueFrom:
              configMapKeyRef:
                name: manifest-global
                key: dictionary_url
          - name: GEN3_HOSTNAME
            valueFrom:
              configMapKeyRef:
                name: manifest-global
                key: hostname
          - name: ROOT_NODE
            value: file
          - name: EXTRA_NODES
            value: ''
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: sheepdog-dbcreds
                key: host
          - name: DB_DATABASE
            valueFrom:
              secretKeyRef:
                name: sheepdog-dbcreds
                key: database
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: sheepdog-dbcreds
                key: username
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: sheepdog-dbcreds
                key: password
          - name: SHEEPDOG
            valueFrom:
              secretKeyRef:
                name: indexd-service-creds
                key: sheepdog
        volumeMounts:
          - name: pelican-creds-volume
            readOnly: true
            mountPath: /pelican-creds.json
            subPath: config.json
        cpu-limit: '0.5'
        memory-limit: 1Gi
      volumes:
        - name: pelican-creds-volume
          secret:
            secretName: pelicanservice-g3auto
      restart_policy: Never
    - name: batch-export
      action: batch-export
      activeDealineSeconds: 600
      serviceAccountName: sower-service-account
      container:
        name: job-task
        image: quay.io/cdis/batch-export:2025.09
        pull_policy: Always
        env:
          - name: BUCKET
            value: sower-jobs-bucket
          - name: GEN3_HOSTNAME
            valueFrom:
              configMapKeyRef:
                name: manifest-global
                key: hostname
        cpu-limit: '1'
        memory-limit: 1Gi
      restart_policy: Never
ssjdispatcher:
  replicaCount: 2
  autoscaling:
    enabled: true
  image:
    repository: quay.io/cdis/ssjdispatcher
    tag: '2025.09'
  enabled: true
  indexing: quay.io/cdis/indexs3client:2025.09
  ssjcreds:
    sqsUrl: https://sqs.us-east-1.amazonaws.com/707767160287/gen3-helm-data-upload-bucket
    jobPattern: s3://gen3-helm-data-upload-bucket/<environment name>/*
    jobPassword: replace_with_password
    metadataservicePassword: replace_with_password
  serviceAccount:
    create: true
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::707767160287:role/ssjdispatcher-role
    name: ssjdispatcher-service-account
  jobServiceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::707767160287:role/ssjdispatcher-role-job
  externalSecrets:
    createK8sSsjdispatcherSecret: true
  gen3Namespace: default
sheepdog:
  replicaCount: 2
  autoscaling:
    enabled: true
  resources:
    requests:
      memory: 105Mi
      cpu: 15m
  enabled: true
  authNamespace: ''
  image:
    repository: quay.io/cdis/sheepdog
    tag: '2025.09'
  fenceUrl: https://hostname/user
peregrine:
  replicaCount: 2
  autoscaling:
    enabled: true
  resources:
    requests:
      memory: 105Mi
      cpu: 15m
  enabled: true
  image:
    repository: quay.io/cdis/peregrine
    tag: '2025.09'
    pullPolicy: Always
requestor:
  replicaCount: 2
  autoscaling:
    enabled: true
  enabled: true
  image:
    repository: quay.io/cdis/requestor
    tag: '2025.09'
audit:
  replicaCount: 2
  autoscaling:
    enabled: true
  env:
    - name: ARBORIST_URL
      valueFrom:
        configMapKeyRef:
          name: manifest-global
          key: arborist_url
          optional: true
  externalSecrets:
    createK8sAuditSecret: true
  image:
    repository: quay.io/cdis/audit-service
    tag: '2025.09'
  server:
    pull_from_queue: true
    debug: true
    sqs:
      region: us-east-1
      url: https://sqs.us-east-1.amazonaws.com/707767160287/audit-service-sqs
  enabled: true
cedar:
  enabled: true
  autoscaling:
    enabled: true
  externalSecrets:
    cedarG3auto: ci-cedar-g3auto
    cedarAPIKey: ci-cedar-directory-id
    cedarDirectoryId: ci-cedar-api-key
  image:
    repository: quay.io/cdis/cedar-wrapper-service
    tag: master
ambassador:
  replicaCount: 2
  autoscaling:
    enabled: true
  enabled: true
  image:
    repository: quay.io/datawire/ambassador
    tag: 1.4.2
arborist:
  replicaCount: 2
  autoscaling:
    enabled: true
  resources:
    requests:
      memory: 105Mi
      cpu: 15m
  enabled: true
  image:
    repository: quay.io/cdis/arborist
    tag: '2025.09'
revproxy:
  replicaCount: 2
  autoscaling:
    enabled: true
  ingress:
    enabled: true
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/tags: Environment=devplanetv2
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:707767160287:certificate/f427a646-94fd-4b91-8bcd-80f5920c1e46
      alb.ingress.kubernetes.io/group.name: devplanetv2
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
      alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig":
        { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
      alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS13-1-2-FIPS-2023-04
    className: alb
    hosts:
      - host: HOSTNAME
        paths:
          - path: /
            pathType: Prefix
    resources:
      requests:
        memory: 105Mi
        cpu: 15m
  image:
    tag: '2025.09'
wts:
  replicaCount: 2
  autoscaling:
    enabled: true
  enabled: true
  image:
    repository: quay.io/cdis/workspace-token-service
    tag: '2025.09'
  externalSecrets:
    createWtsOidcClientSecret: true
    createK8sWtsSecret: true
manifestservice:
  replicaCount: 2
  autoscaling:
    enabled: true
  image:
    repository: quay.io/cdis/manifestservice
    tag: '2025.09'
  env:
    - name: REQUESTS_CA_BUNDLE
      value: /etc/ssl/certs/ca-certificates.crt
    - name: MANIFEST_SERVICE_CONFIG_PATH
      value: /var/gen3/config/config.json
    - name: GEN3_DEBUG
      value: 'False'
  manifestserviceG3auto:
    hostname: null
    bucketName: gen3-helm-manifest-bucket
    prefix: test
  externalSecrets:
    createK8sManifestServiceSecret: true
ohif-viewer:
  replicaCount: 2
  autoscaling:
    enabled: true
  enabled: true
  image:
    repository: quay.io/cdis/ohif-viewer
    tag: gen3-v3.8.0
dicom-server:
  replicaCount: 2
  autoscaling:
    enabled: true
  enabled: false
  image:
    repository: quay.io/cdis/gen3-orthanc
    tag: master
gen3-user-data-library:
  replicaCount: 2
  autoscaling:
    enabled: true
  enabled: true
  image:
    repository: quay.io/cdis/gen3-user-data-library
    tag: '2025.09'
  externalSecrets:
    createK8sGen3UserDataLibrarySecret: true
access-backend:
  enabled: false
orthanc:
  replicaCount: 2
  autoscaling:
    enabled: true
  enabled: true
  image:
    repository: quay.io/cdis/gen3-orthanc
    tag: orthancteam-master-gen3-24.3.5
  externalSecrets:
    orthancS3G3Auto: ci-orthanc-s3-g3auto
