global:
  hostname: ci-perf
  dictionaryUrl: https://s3.amazonaws.com/dictionary-artifacts/anvil/master/schema.json
  pdb: true
  aws:
    externalSecrets:
      enabled: true
      externalSecretAwsCreds: ci-aws-config
    secretStoreServiceAccount:
      enabled: true
      name: secret-store-sa
      roleArn: arn:aws:iam::707767160287:role/devplanetv2-external-secrets-sa
    sower_role: sower-jobs-role
  externalSecrets:
    deploy: true
    dbCreate: true
  fenceURL: https://ci-perf.ci.planx-pla.net/user
  manifestGlobalExtraValues:
    google_enabled: true
  tierAccessLevel: libre

mutatingWebhook:
  enabled: false

postgresql:
  primary:
    persistence:
      enabled: true
      size: 1Gi
  image:
    registry: quay.io
    repository: cdis/postgresql
    tag: 14.5.0-debian-11-r35

maxUnavailable: ""
elasticsearch:
  maxUnavailable: ""
  volumeClaimTemplate:
    resources:
      requests:
        storage: 1Gi
