apiVersion: batch/v1
kind: CronJob
metadata:
  name: spinup-cronjob
  namespace: default
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      activeDeadlineSeconds: 3600
      backoffLimit: 0
      template:
        metadata:
          labels:
            app: gen3job
        spec:
          affinity:
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - preference:
                    matchExpressions:
                      - key: karpenter.sh/capacity-type
                        operator: In
                        values:
                          - on-demand
                  weight: 100
                - preference:
                    matchExpressions:
                      - key: eks.amazonaws.com/capacityType
                        operator: In
                        values:
                          - ONDEMAND
                  weight: 99
          containers:
            - args:
                - -c
                - |
                  #!/usr/bin/env bash

                  kubectl get ns -o custom-columns=NAME:.metadata.name --no-headers  |  grep -vFxf /blacklist  | xargs -r -n1 kubectl scale deployments --all --replicas=1 -n
                  exit 0
              command:
                - /bin/bash
              image: quay.io/cdis/awshelper:master
              imagePullPolicy: Always
              name: awshelper
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              volumeMounts:
                - mountPath: /blacklist
                  name: shutdown-blacklist
                  readOnly: true
                  subPath: blacklist
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext:
            fsGroup: 1000
          serviceAccount: scale-deploy-sa
          serviceAccountName: scale-deploy-sa
          terminationGracePeriodSeconds: 30
          volumes:
            - configMap:
                defaultMode: 420
                name: shutdown-blacklist
              name: shutdown-blacklist
      ttlSecondsAfterFinished: 3600
  schedule: 0 6 * * 1-5
  successfulJobsHistoryLimit: 3
  suspend: false
