global:
  dev: false
  # uncomment once we cutover, so we can use shared ALB
  #environment: "unfunded"
  hostname: "caninedc.org"
  aws:
    enabled: true
    useLocalSecret:
      enabled: true
      localSecretName: external-secrets-canine-secret
  revproxyArn: arn:aws:acm:us-east-1:662843554732:certificate/5874502e-5b67-415f-80ee-dcb814d2883f
  dictionaryUrl: "https://s3.amazonaws.com/dictionary-artifacts/canine_dictionary/1.1.0/schema.json"
  postgres:
    dbCreate: false
    externalSecret: "pg-master"
  externalSecrets:
    # -- (bool) Will use ExternalSecret resources to pull secrets from Secrets Manager instead of creating them locally. Be cautious as this will override secrets you have deployed.
    deploy: true
  pdb: true

arborist:
  enabled: true
  externalSecrets:
    dbcreds: "canineprod-arborist"
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/arborist
    tag: 2023.12

aws-es-proxy:
  esEndpoint: vpc-unfunded-gen3-metadata-2-tf3gyjftzrgm5asaxuvqxxwv2m.us-east-1.es.amazonaws.com
  externalSecrets:
    awsCreds: "canineprod-aws-es-proxy-creds"
  enabled: true
  image:
    repository: quay.io/cdis/aws-es-proxy
    tag: "v1.3.1"
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::662843554732:role/opensearch-access-role
  volumeMounts: []

indexd:
  defaultPrefix: "dg.C78ne/"

  externalSecrets:
    dbcreds: "canineprod-indexd"
    serviceCreds: "canineprod-indexd-service-creds"

  enabled: true
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/indexd
    tag: 2023.12

peregrine:
  externalSecrets:
    dbcreds: "canineprod-peregrine"
  enabled: true
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/peregrine
    tag: feat_jq-audience
    pullPolicy: Always

revproxy:
  enabled: true
  replicaCount: 2
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/nginx
    tag: 2023.12

sheepdog:
  externalSecrets:
    dbcreds: "canineprod-sheepdog"
  enabled: true
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/sheepdog
    tag: 2023.12

manifestservice:
  enabled: true
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/manifestservice
    tag: 2023.12
  externalSecrets:
    manifestserviceG3auto: "canine-manifestservice-g3auto"

etl:
  enabled: true
  spark:
    image:
      repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/gen3-spark
      tag: 2023.12
  tube:
    image:
      repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/tube
      tag: 2023.12

sower:
  enabled: true
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/sower
    tag: 2023.12
  externalSecrets:
    pelicanserviceG3auto: "canine-pelicanservice-g3auto"

ssjdispatcher:
  enabled: true
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/ssjdispatcher
    tag: 2023.12

metadata:
  externalSecrets:
    dbcreds: "canineprod-metadata"
    metadataG3auto: "canine-metadata-g3auto"
  enabled: true
  esEndpoint: http://elasticsearch:9200
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/metadata-service
    tag: 2023.12

# disabling workspace services
ambassador:
  enabled: true
wts:
  enabled: false
hatchery:
  enabled: false

# disabling audit service
audit:
  enabled: false
