apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-level-resources
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    helm:
      releaseName: cluster-level-resources
      valueFiles:
      - ../pdp-external/cluster-values/cluster-values.yaml
    path: cluster-level-resources
    repoURL: https://github.com/uc-cdis/gen3-gitops.git
    targetRevision: master
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
