cluster: emalinowskiv1
project: dev

accountNumber: "707767160287"

configuration:
  configurationRevision: feat/no-cluster-endpoint-needed

alb-controller:
  enabled: true
  configuration:
    enabled: false

aws-s3-mountpoint:
  enabled: false
  configuration:
    enabled: false

calico:
  enabled: true
  configuration:
    enabled: false

coreDNS:
  enabled: true
  configuration:
    enabled: false

crossplane:
  enabled: true

crossplane-crds:
  enabled: true
  iamRoleName: "crossplane-test-role"

ebs-csi-driver:
  enabled: true
  configuration:
    enabled: false

external-secrets:
  enabled: true
  configuration:
    enabled: false

fluentd:
  enabled: false
  configuration:
    enabled: false

kube-state-metrics:
  enabled: false
  configuration:
    enabled: false

grafana-alloy:
  enabled: false
  configuration:
    enabled: false

karpenter:
  enabled: true
  targetRevision: "1.0.8"
  configuration:
    enabled: true

karpenter-crds:
  amiSelectorName: "1-31-EKS-FIPS*"
  enabled: true
  selectorTag: emalinowskiv1
  migration: true

kube-proxy:
  enabled: true

vpc-cni:
  enabled: true
  configuration:
    enabled: false
