cluster: emalinowskiv1
project: dev

accountNumber: "707767160287"

configuration:
  configurationRevision: master

alb-controller:
  enabled: true
  configuration:
    enabled: false

aws-s3-mountpoint:
  enabled: false
  configuration:
    enabled: false

calico:
  enabled: true
  configuration:
    enabled: false

coreDNS:
  enabled: true
  configuration:
    enabled: false

ebs-csi-driver:
  enabled: true
  configuration:
    enabled: false

fluentd:
  enabled: false
  configuration:
    enabled: false

kube-state-metrics:
  enabled: false
  configuration:
    enabled: false

grafana-alloy:
  enabled: false
  configuration:
    enabled: false

karpenter:
  enabled: true
  targetRevision: "1.6.3"
  configuration:
    enabled: true

karpenter-crds:
  amiSelectorName: "EKS-1-33-al23*"
  consolidationPolicy: "WhenEmptyOrUnderutilized"
  consolidateAfter: "5m"
  expireAfter: "72h"
  enabled: true
  selectorTag: emalinowskiv1
  migration: true

vpc-cni:
  enabled: true
  configuration:
    enabled: false
