cluster: emalinowskiv1
project: dev

eksClusterEndpoint: https://D593510942408447DE83F479C3C2B5E3.gr7.us-east-1.eks.amazonaws.com

accountNumber: "707767160287"

configuration:
  configurationRevision: feat/karpenter-1-0

alb-controller:
  enabled: true
  configuration:
    enabled: false

aws-s3-mountpoint:
  enabled: false
  configuration:
    enabled: false

calico:
  enabled: true
  configuration:
    enabled: false

coreDNS:
  enabled: true
  configuration:
    enabled: false

ebs-csi-driver:
  enabled: true
  configuration:
    enabled: false

fluentd:
  enabled: false
  configuration:
    enabled: false

kube-state-metrics:
  enabled: false
  configuration:
    enabled: false

grafana-alloy:
  enabled: false
  configuration:
    enabled: false

karpenter:
  enabled: true
  targetRevision: v1.0.8
  configuration:
    enabled: false
  controller:
    image:
      tag: "1.0.8"
      digest: "sha256:157f478f5db1fe999f5e2d27badcc742bf51cc470508b3cebe78224d0947674f"

karpenter-crds:
  amiSelectorName: "1-31-EKS-FIPS*"
  enabled: true
  selectorTag: emalinowskiv1
  migration: true

vpc-cni:
  enabled: true
  configuration:
    enabled: false
