cluster: headneck
project: headneck
accountNumber: "419939494982"

alb-controller:
  enabled: true
  targetRevision: "1.13.4"
  configuration:
    enabled: true

aws-s3-mountpoint:
  enabled: true
  targetRevision: "1.2.0"
  configuration:
    enabled: false

calico:
  enabled: true
  targetRevision: v3.33.0
  configuration:
    enabled: true

coreDNS:
  enabled: true
  targetRevision: v1.43.1
  configuration:
    enabled: false

ebs-csi-driver:
  enabled: true
  targetRevision: "1.48.0"
  configuration:
    enabled: false

fluentd:
  enabled: false
  configuration:
    enabled: false

grafana-alloy:
  enabled: true
  targetRevision: "1.4.0"
  configuration:
    enabled: false

karpenter:
  enabled: true
  targetRevision: "1.6.3"

karpenter-crds:
  amiSelectorName: "EKS-1-33-al23*"
  enabled: true
  selectorTag: headneck
  migration: true
  default:
    nodeClassRef:
      apiVersion: karpenter.k8s.aws/v1
      kind: EC2NodeClass
      name: default
    amiFamily: AL2023
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: "5m"
    expireAfter: "72h"
    volumeSize: 80Gi
    requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values:
      - on-demand
      - spot
    - key: kubernetes.io/arch
      operator: In
      values:
      - amd64
    - key: node.kubernetes.io/instance-type
      operator: In
      values:
      - m8i-flex.large
      - m8i-flex.xlarge
      - m8i-flex.2xlarge
      - r8i-flex.large
      - r8i-flex.xlarge
      - r8i-flex.2xlarge
  jupyter:
    enabled: false
    nodeClassRef:
      apiVersion: karpenter.k8s.aws/v1
      kind: EC2NodeClass
      name: jupyter
    amiFamily: AL2023
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: "5m"
    expireAfter: "72h"
    volumeSize: 80Gi
  workflow:
    enabled: false
    nodeClassRef:
      apiVersion: karpenter.k8s.aws/v1
      kind: EC2NodeClass
      name: workflow
    amiFamily: AL2023
    consolidateAfter: "5m"
    expireAfter: "72h"
    volumeSize: 80Gi

kube-state-metrics:
  enabled: true
  targetRevision: "2.16.0"
  configuration:
    enabled: false

vpc-cni:
  enabled: true
  targetRevision: v1.20.1
  configuration:
    enabled: false
