global:
  dev: false
  # uncomment once we cutover, so we can use shared ALB
  #environment: "unfunded"
  hostname: "diseasedatahub.org"
  origins_allow_credentials: ["https://tb.diseasedatahub.org", "https://aids.diseasedatahub.org", "https://microbiome.diseasedatahub.org", "https://flu.diseasedatahub.org"]
  manifestGlobalExtraValues:
    cookie_domain: "diseasedatahub.org"
  aws:
    enabled: true
    useLocalSecret:
        enabled: true
        localSecretName: external-secrets-niaiddata-secret
  revproxyArn: arn:aws:acm:us-east-1:662843554732:certificate/176af316-6175-4213-af46-766e0bbd8b5a
  dictionaryUrl: "https://s3.amazonaws.com/dictionary-artifacts/chords-health-dictionary/0.1.0/schema.json"
  postgres:
    dbCreate: false
    externalSecret: "niaiddata-master-password"
  externalSecrets:
    # -- (bool) Will use ExternalSecret resources to pull secrets from Secrets Manager instead of creating them locally. Be cautious as this will override secrets you have deployed.
    deploy: true

arborist:
  enabled: true
  externalSecrets:
    dbcreds: "niaiddata-arborist-db-creds"
  image:
    repository: quay.io/cdis/arborist
    tag: 2023.12

aws-es-proxy:
  esEndpoint: vpc-unfunded-gen3-metadata-2-tf3gyjftzrgm5asaxuvqxxwv2m.us-east-1.es.amazonaws.com
  externalSecrets:
    awsCreds: "niaiddata-aws-es-proxy-creds"
  enabled: true
  image:
    repository: quay.io/cdis/aws-es-proxy
    tag: v1.3.1

indexd:
  # defaultPrefix: "dg.C78ch/"
  externalSecrets:
    dbcreds: "niaiddata-indexd-db-creds"
    serviceCreds: "niaiddata-indexd-service-creds"

  enabled: true
  image:
    repository: quay.io/cdis/indexd
    tag: 2023.12

peregrine:
  externalSecrets:
    dbcreds: "niaiddata-peregrine-db-creds"
  enabled: true
  image:
    repository: quay.io/cdis/peregrine
    tag: feat_jq-audience
    pullPolicy: Always

revproxy:
  enabled: true
  image:
    repository: quay.io/cdis/nginx
    tag: 2023.12

sheepdog:
  externalSecrets:
    dbcreds: "niaiddata-sheepdog-db-creds"
  enabled: true
  image:
    repository: quay.io/cdis/sheepdog
    tag: 2023.12

manifestservice:
  enabled: true
  image:
    repository: quay.io/cdis/manifestservice
    tag: 2023.12
  externalSecrets:
    manifestserviceG3auto: "niaiddata-manifestservice-g3auto"

ambassador:
  enabled: true

wts:
  externalSecrets:
    dbcreds: "niaiddata-wts-db-creds"
  enabled: true
  image:
    repository: quay.io/cdis/workspace-token-service
    tag: 2023.12

# disabled services
pelican:
  enabled: false
pidgin:
  enabled: false
sower:
  enabled: false
ssjdispatcher:
  enabled: false
audit:
  enabled: false
argo-wrapper:
  enabled: false
metadata:
  enabled: false
