cluster: healworkspaces
project: heal

alb-controller:
  enabled: true
  configuration:
    enabled: false

aws-s3-mountpoint:
  enabled: true
  configuration:
    enabled: false

calico:
  enabled: true
  configuration:
    enabled: false

coreDNS:
  enabled: true
  configuration:
    enabled: false

ebs-csi-driver:
  enabled: false
  configuration:
    enabled: false

fluentd:
  enabled: true
  configuration:
    enabled: false

kube-state-metrics:
  enabled: true
  configuration:
    enabled: false

grafana-alloy:
  enabled: true
  configuration:
    enabled: false

karpenter-crds:
  enabled: true
  selectorTag: healworkspaces

vpc-cni:
  enabled: true
  configuration:
    enabled: false
