apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - path: helm/karpenter-templates
      repoURL: https://github.com/uc-cdis/gen3-helm
      targetRevision: feat/karpenter-templates
      helm:
        releaseName: karpenter-templates
        valueFiles:
          - $values/qa.planx-pla.net/values/karpenter-templates.yaml
    - repoURL: 'https://github.com/uc-cdis/gen3-gitops.git'
      targetRevision: feat/karpenter-qav1
      ref: values
    - repoURL: 'https://github.com/aws/karpenter-provider-aws'
      targetRevision: v0.32.1
      path: charts/karpenter
      helm:
        releaseName: karpenter
        valueFiles:
          - $values/qa.planx-pla.net/values/karpenter.yaml  

  destination:
    server: "https://kubernetes.default.svc"
    namespace: karpenter
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
