global:
  dev: false
  hostname: tb.diseasedatahub.org
  origins_allow_credentials:
    - https://diseasedatahub.org
  manifestGlobalExtraValues:
    fence_url: https://diseasedatahub.org/user
    arborist_url: http://arborist-service.diseasedatahub.svc.cluster.local
    indexd_url: https://diseasedatahub.org/index/
    workspace_url: https://diseasedatahub.org/lw-workspace
    manifest_service_url: https://diseasedatahub.org/manifests
    wts_url: https://diseasedatahub.org/wts/oauth2/
    cookie_domain: diseasedatahub.org
    des_namespace: diseasedatahub
  aws:
    enabled: true
    useLocalSecret:
      enabled: true
      localSecretName: external-secrets-tb-secret
    wafv2:
      enabled: true
      wafAclArn: arn:aws:wafv2:us-east-1:662843554732:regional/webacl/unfunded-waf/e10ae423-8e4e-48ba-9a0e-52b43f28f6d4
  revproxyArn: arn:aws:acm:us-east-1:662843554732:certificate/86eca425-c2c3-4911-a49f-20beca8c7e99
  dictionaryUrl: https://s3.amazonaws.com/dictionary-artifacts/tb-datadictionary/1.1.5/schema.json
  postgres:
    dbCreate: false
    externalSecret: tb-master-password
  externalSecrets:
    deploy: true
arborist:
  resources:
    requests:
      memory: 105Mi
      cpu: 15m
  enabled: true
  externalSecrets:
    dbcreds: tb-arborist-db-creds
  image:
    repository: quay.io/cdis/arborist
    tag: '2025.10'
aws-es-proxy:
  resources:
    requests:
      memory: 105Mi
      cpu: 15m
  esEndpoint: vpc-unfunded-gen3-metadata-2-tf3gyjftzrgm5asaxuvqxxwv2m.us-east-1.es.amazonaws.com
  externalSecrets:
    awsCreds: tb-aws-es-proxy-creds
  enabled: true
  image:
    repository: quay.io/cdis/aws-es-proxy
    tag: v1.3.1
indexd:
  resources:
    requests:
      memory: 105Mi
      cpu: 15m
  externalSecrets:
    dbcreds: tb-indexd-db-creds
    serviceCreds: tb-indexd-service-creds
  enabled: true
  image:
    repository: quay.io/cdis/indexd
    tag: '2025.10'
peregrine:
  resources:
    requests:
      memory: 105Mi
      cpu: 15m
  externalSecrets:
    dbcreds: tb-peregrine-db-creds
  enabled: true
  image:
    repository: quay.io/cdis/peregrine
    tag: '2025.10'
    pullPolicy: Always
revproxy:
  resources:
    requests:
      memory: 105Mi
      cpu: 15m
  enabled: true
  image:
    repository: quay.io/cdis/nginx
    tag: '2025.10'
sheepdog:
  resources:
    requests:
      memory: 105Mi
      cpu: 15m
  externalSecrets:
    dbcreds: tb-sheepdog-db-creds
  enabled: true
  image:
    repository: quay.io/cdis/sheepdog
    tag: '2025.10'
manifestservice:
  resources:
    requests:
      memory: 105Mi
      cpu: 15m
  enabled: true
  image:
    repository: quay.io/cdis/manifestservice
    tag: '2025.10'
  externalSecrets:
    manifestserviceG3auto: tb-manifestservice-g3auto
wts:
  resources:
    requests:
      memory: 105Mi
      cpu: 15m
  externalSecrets:
    dbcreds: tb-wts-db-creds
  enabled: true
  image:
    repository: quay.io/cdis/workspace-token-service
    tag: '2025.10'
ambassador:
  enabled: false
hatchery:
  enabled: false
audit:
  enabled: false
argo-wrapper:
  enabled: false
pidgin:
  enabled: false
sower:
  enabled: false
ssjdispatcher:
  enabled: false
metadata:
  enabled: false
