apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gen3-qa-mickey
  namespace: argocd
spec:
  project: default
  sources:
    - path: helm/gen3
      repoURL: https://github.com/uc-cdis/gen3-helm
      targetRevision: feat/deployment-canary
      helm:
        releaseName: gen3-qa-mickey
        valueFiles:
          - $values/qaplanetv1/qa-mickey.planx-pla.net/values/values.yaml
          - $values/qaplanetv1/qa-mickey.planx-pla.net/values/fence.yaml
          - $values/qaplanetv1/qa-mickey.planx-pla.net/values/portal.yaml
    - repoURL: 'https://github.com/uc-cdis/gen3-gitops.git'
      targetRevision: master
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: qa-mickey-helm
  syncPolicy:
    syncOptions:
    - CreateNamespace=false
    automated:
      selfHeal: true
