apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gen3-tb
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - path: helm/gen3
      repoURL: https://github.com/uc-cdis/gen3-helm
      targetRevision: "feat/GPE-1032"
      helm:
        releaseName: tbargo
        valueFiles:
          - $values/tb.diseasedatahub.org/values/values.yaml
          - $values/tb.diseasedatahub.org/values/fence.yaml
          - $values/tb.diseasedatahub.org/values/portal.yaml
          - $values/tb.diseasedatahub.org/values/guppy.yaml
    - repoURL: 'https://github.com/uc-cdis/gen3-gitops.git'
      targetRevision: master
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: tbhelm
  syncPolicy:
    syncOptions:
    - CreateNamespace=false
    automated:
      selfHeal: true
