# The name of the cluster this configuration is going to. This should match the name of the directory configuration
# is stored in
cluster: pdp-commons
project: pdp

grafana-alloy:
  enabled: true
  configuration:
    enabled: false
