apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eks-resources
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/uc-cdis/gen3-gitops.git
    targetRevision: master
    path: eks-resources
  syncPolicy:
    automated:
      selfHeal: true
