cluster: midrcvalidate
project: midrc

accountNumber: "813684607867"

alb-controller:
  enabled: true
  configuration:
    enabled: false

aws-s3-mountpoint:
  enabled: true
  configuration:
    enabled: false

calico:
  enabled: true
  configuration:
    enabled: false

coreDNS:
  enabled: true
  configuration:
    enabled: false

ebs-csi-driver:
  enabled: true
  configuration:
    enabled: false

external-secrets:
  enabled: true

fluentd:
  enabled: false
  configuration:
    enabled: false

kube-state-metrics:
  enabled: true
  configuration:
    enabled: false

grafana-alloy:
  enabled: true
  configuration:
    enabled: false

karpenter-crds:
  amiSelectorName: "1-31-EKS-FIPS*"
  enabled: true
  selectorTag: midrcvalidate
  migration: true
  workflow:
    sgSelector: midrcvalidate

karpenter:
  enabled: true
  targetRevision: "1.0.8"

vpc-cni:
  enabled: true
  configuration:
    enabled: false
