global:
  dev: false
  # uncomment once we cutover, so we can use shared ALB
  #environment: "unfunded"
  hostname: "tb.diseasedatahub.org"
  aws: 
    enabled: true
    useLocalSecret:
        enabled: true
        localSecretName: external-secrets-tb-secret 
  revproxyArn: arn:aws:acm:us-east-1:662843554732:certificate/5874502e-5b67-415f-80ee-dcb814d2883f
  dictionaryUrl: "https://s3.amazonaws.com/dictionary-artifacts/tb-datadictionary/1.1.5/schema.json"
  postgres:
    dbCreate: false
    externalSecret: "tb-master-password"
  externalSecrets:
    # -- (bool) Will use ExternalSecret resources to pull secrets from Secrets Manager instead of creating them locally. Be cautious as this will override secrets you have deployed.
    deploy: true

arborist:
  enabled: true
  externalSecrets:
    dbcreds: "tb-arborist-db-creds"
  image: 
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/arborist
    tag: 2023.12

aws-es-proxy:
  esEndpoint: vpc-unfunded-gen3-metadata-2-tf3gyjftzrgm5asaxuvqxxwv2m.us-east-1.es.amazonaws.com
  externalSecrets:
    awsCreds: "tb-aws-es-proxy-creds"
  enabled: true
  image:
    repository: quay.io/cdis/aws-es-proxy
    tag: v1.3.1

indexd:
  # defaultPrefix: "dg.C78ch/"
  externalSecrets:
    dbcreds: "tb-indexd-db-creds" 
    serviceCreds: "tb-indexd-service-creds"
  
  enabled: true
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/indexd
    tag: 2023.12

peregrine:
  externalSecrets:
    dbcreds: "tb-peregrine-db-creds" 
  enabled: true
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/peregrine
    tag: feat_jq-audience 
    pullPolicy: Always

pidgin:
  enabled: false

revproxy:
  enabled: true
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/nginx
    tag: 2023.12

sheepdog:
  externalSecrets:
    dbcreds: "tb-sheepdog-db-creds" 
  enabled: true
  volumeMounts:
    - name: "config-volume"
      readOnly: true
      mountPath: "/var/www/sheepdog/settings.py"
      subPath: "wsgi.py"

  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/sheepdog
    tag: 2023.12

manifestservice:
  enabled: true
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/manifestservice
    tag: 2023.12
  externalSecrets:
    manifestserviceG3auto: "tb-manifestservice-g3auto" 

sower:
  enabled: false

ssjdispatcher:
  enabled: false
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/ssjdispatcher
    tag: 2023.12

metadata:
  useAggMds: False
  externalSecrets:
    dbcreds: "tb-metadata-db-creds"
  enabled: false
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/metadata-service
    tag: 2023.12
    esEndpoint: http://elasticsearch:9200

# disabling workspace services
ambassador:
  enabled: false
wts:
  externalSecrets:
    dbcreds: "tb-wts-db-creds"
  enabled: false
hatchery:
  enabled: false

# disabling audit service
audit:
  enabled: false

# disabling argo-wrapper service
argo-wrapper:
  enabled: false
