cluster: externalgen3
project: externalgen3
accountNumber: "637423560817"

configuration:
  configurationRevision: calico-dev

alb-controller:
  enabled: true
  targetRevision: "1.13.4"
  configuration:
    enabled: true

aws-s3-mountpoint:
  enabled: true
  targetRevision: "1.2.0"
  configuration:
    enabled: false

calico:
  enabled: true
  targetRevision: v3.33.0
  configuration:
    enabled: false

coreDNS:
  enabled: true
  targetRevision: v1.43.1
  configuration:
    enabled: false

ebs-csi-driver:
  enabled: true
  targetRevision: "1.48.0"
  configuration:
    enabled: false

fluentd:
  enabled: false
  configuration:
    enabled: false

kube-state-metrics:
  enabled: true
  targetRevision: "2.16.0"
  configuration:
    enabled: false

grafana-alloy:
  enabled: true
  targetRevision: "1.4.0"
  configuration:
    enabled: false

karpenter:
  enabled: true
  targetRevision: "1.6.3"

karpenter-crds:
  amiSelectorName: "EKS-1-33-al23*"
  enabled: true
  selectorTag: externalgen3
  migration: true
  default:
    nodeClassRef:
      apiVersion: karpenter.k8s.aws/v1
      kind: EC2NodeClass
      name: default
    amiFamily: AL2023
    consolidationPolicy: "WhenUnderutilized"
    consolidateAfter: "5m"
    expireAfter: "72h"
    volumeSize: 80Gi
  jupyter:
    enabled: false
    nodeClassRef:
      apiVersion: karpenter.k8s.aws/v1
      kind: EC2NodeClass
      name: jupyter
    amiFamily: AL2023
    consolidationPolicy: "WhenUnderutilized"
    consolidateAfter: "5m"
    expireAfter: "72h"
    volumeSize: 80Gi
  workflow:
    enabled: false
    nodeClassRef:
      apiVersion: karpenter.k8s.aws/v1
      kind: EC2NodeClass
      name: workflow
    amiFamily: AL2023
    consolidateAfter: "5m"
    expireAfter: "72h"
    volumeSize: 80Gi

vpc-cni:
  enabled: true
  targetRevision: v1.20.1
  configuration:
    enabled: false
