cluster: externalgen3
project: externalgen3

accountNumber: "637423560817"

configuration:
  configurationRevision: master

alb-controller:
  enabled: true

aws-s3-mountpoint:
  enabled: true
  configuration:
    enabled: false

calico:
  enabled: true
  targetRevision: v3.27.0
  configuration:
    enabled: false

coreDNS:
  enabled: true
  targetRevision: v1.29.0
  configuration:
    enabled: false

ebs-csi-driver:
  enabled: false
  configuration:
    enabled: false

fluentd:
  enabled: false
  configuration:
    enabled: false

kube-state-metrics:
  enabled: true
  configuration:
    enabled: false

grafana-alloy:
  enabled: true
  targetRevision: 0.4.0
  configuration:
    enabled: false

karpenter:
  enabled: true
  targetRevision: v0.32.9

karpenter-crds:
  amiSelectorName: "1-31-EKS-FIPS*"
  enabled: true
  selectorTag: externalgen3
  migration: true
  default:
    consolidationPolicy: "WhenUnderutilized"
    consolidateAfter: ""

vpc-cni:
  enabled: true
  targetRevision: v1.16.2
  configuration:
    enabled: false
