cluster: pdp-external
project: externalgen3

eksClusterName: externalgen3

accountNumber: "637423560817"

alb-controller:
  enabled: true
  configuration:
    enabled: true

aws-s3-mountpoint:
  enabled: true
  configuration:
    enabled: false

calico:
  enabled: true
  targetRevision: v3.27.0
  configuration:
    enabled: false

coreDNS:
  enabled: true
  targetRevision: v1.29.0
  configuration:
    enabled: false

ebs-csi-driver:
  enabled: false
  configuration:
    enabled: false

fluentd:
  enabled: false
  configuration:
    enabled: false

kube-state-metrics:
  enabled: true
  configuration:
    enabled: false

grafana-alloy:
  enabled: true
  targetRevision: 0.4.0
  configuration:
    enabled: false

karpenter:
  enabled: true
  targetRevision: "1.0.8"

karpenter-crds:
  amiSelectorName: "1-31-EKS-FIPS*"
  enabled: true
  selectorTag: externalgen3
  migration: true
  default:
    consolidationPolicy: "WhenEmptyOrUnderutilized"
    consolidateAfter: "5m"

vpc-cni:
  enabled: true
  targetRevision: v1.16.2
  configuration:
    enabled: false
