cluster: chordsprod
project: chords

grafana-alloy:
  enabled: true
  configuration:
    enabled: false

karpenter-crds:
  amiSelectorName: "1-31-EKS-FIPS*"
  enabled: true
  selectorTag: chords
  migration: true
