apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gen3-bdcat-stagingdatastage
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - path: helm/gen3
      repoURL: https://github.com/uc-cdis/gen3-helm
      targetRevision: feat/fixing-hpa-type
      helm:
        releaseName: gen3-bdcat-stagingdatastage
        valueFiles:
          - $values/bdcat-stagingdatastage/staging.gen3.biodatacatalyst.nhlbi.nih.gov/values/values.yaml
    - repoURL: 'https://github.com/uc-cdis/gen3-gitops.git'
      targetRevision: master
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: bdcat-stagingdatastage-helm
  syncPolicy:
    syncOptions:
    - CreateNamespace=false
    automated:
      selfHeal: true
