apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: calico
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: aws-vpc-cni
      repoURL: https://docs.tigera.io/calico/charts
      targetRevision: "v3.27.0"
      helm:
        releaseName: calico
        valueFiles:
          - $values/eks-resources/values/calico.yaml
    - repoURL: 'https://github.com/uc-cdis/gen3-gitops.git'
      targetRevision: feat/eks-resources
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system
  syncPolicy:
    syncOptions:
    - CreateNamespace=false
    automated:
      selfHeal: true