apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coredns
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: coredns
      repoURL: https://coredns.github.io/helm
      targetRevision: "v1.29.0"
      helm:
        releaseName: coredns
        valueFiles:
          - $values/eks-resources/values/coredns.yaml
    - repoURL: 'https://github.com/uc-cdis/gen3-gitops.git'
      targetRevision: master
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system
  syncPolicy:
    syncOptions:
    - CreateNamespace=false
    automated:
      selfHeal: false
