apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - path: helm/lgtm-distributed
      repoURL: https://github.com/uc-cdis/gen3-helm
      targetRevision: master
      helm:
        valueFiles:
          - $values/eks-resources/values/grafana.yaml
          - $values/eks-resources/values/loki.yaml
          - $values/eks-resources/values/mimir.yaml
          - $values/eks-resources/values/tempo.yaml
    - repoURL: 'https://github.com/uc-cdis/gen3-gitops.git'
      targetRevision: master
      ref: values
    - repoURL: https://grafana.github.io/helm-charts
      chart: alloy
      targetRevision: 0.1.1
      helm:
        valueFiles:
          - $values/eks-resources/values/alloy.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
