apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-s3-mountpoint
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: aws-s3-mountpoint
      repoURL: https://awslabs.github.io/mountpoint-s3-csi-driver
      targetRevision: "v1.4.0"
      helm:
        releaseName: aws-s3-mountpoint

  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system
  syncPolicy:
    syncOptions:
    - CreateNamespace=false
    automated:
      selfHeal: true
