apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vpc-cni
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: aws-vpc-cni
      repoURL: https://aws.github.io/eks-charts
      targetRevision: "v1.16.2"
      helm:
        releaseName: canineprod
        valueFiles:
          - $values/eks-resources/values/vpc-cni.yaml
    - repoURL: 'https://github.com/uc-cdis/gen3-gitops.git'
      targetRevision: feat/eks-resources
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system
  syncPolicy:
    syncOptions:
    - CreateNamespace=false
    automated:
      selfHeal: true