global:
  aws:
    enabled: true
    account: "419939494982"
    awsEsProxyRole: gen3-service/headneck-esproxy-sa
    hatchery_role: arn:aws:iam::419939494982:role/gen3-service/headneck-default-hatchery-sa
    secretStoreServiceAccount:
      enabled: true
      name: external-secrets
      roleArn: arn:aws:iam::419939494982:role/gen3-service/headneck-default-external-secrets-sa
    wafv2:
      # -- (bool) Set to true if using AWS WAFv2
      enabled: true
      # -- (string) ARN for the WAFv2 ACL.
      wafAclArn: "arn:aws:wafv2:us-east-1:419939494982:regional/webacl/headneck-waf/7bf68efb-772e-4ac6-857d-0c73911b9e77"
  dev: false
  externalSecrets:
    deploy: true
  postgres:
    dbCreate: false
    externalSecret: "headneck_aurora-master-password"
  environment: "headneck"
  hostname: "headneckcancerbank.data-commons.org"
  revproxyArn: "arn:aws:acm:us-east-1:419939494982:certificate/04695470-5b09-41a9-bccb-f5da3dd0f5a4"
  dictionaryUrl: "https://s3.amazonaws.com/dictionary-artifacts/hnc_dictionary/0.1.5/schema.json"
  portalApp: gitops
  publicDataSets: false
  tierAccessLevel: "private"
  tierAccessLimit: 100
  fenceURL: https://headneckcancerbank.data-commons.org/user
  # netPolicy:
  #   enabled: true
  #   dbSubnet:
  #     - 172.24.192.128/25
  #     - 172.24.192.0/25
  dispatcherJobNum: "10"
  frontendRoot: "portal"
  ddEnabled: false

ambassador:
  # Lower cost
  resources:
    requests:
      memory: "105Mi"
      cpu: "15m"
  enabled: true

arborist:
  # Lower cost
  resources:
    requests:
      memory: "105Mi"
      cpu: "15m"
  enabled: true
  externalSecrets:
    dbcreds: "headneck_default-arborist-creds"

argo-wrapper:
  enabled: false

audit:
  # Lower cost
  resources:
    requests:
      memory: "105Mi"
      cpu: "15m"
  enabled: true
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::419939494982:role/gen3-service/headneck-default-audit-sa"
  externalSecrets:
    dbcreds: "headneck_default-audit-creds"
    createK8sAuditSecret: true


aws-es-proxy:
  # Lower cost
  resources:
    requests:
      memory: "105Mi"
      cpu: "15m"
  enabled: true
  esEndpoint: vpc-headneck-gen3-metadata-nqv355pim7ge3dduo5kexxoilu.us-east-1.es.amazonaws.com
  externalSecrets:
    awsCreds: "headneck_default-aws-es-proxy-creds"

dicom-server:
  enabled: false
  externalSecrets:
    dbcreds: "headneck_default-dicom-server-creds"

dicom-viewer:
  enabled: false
  externalSecrets:
    dbcreds: "headneck_default-dicom-viewer-creds"

etl:
  image:
    tube:
      # -- (string) Overrides the image tag whose default is the chart appVersion.
      tag: "jawad-debug"
      # tag: "2025.09"
      pullPolicy: Always
  esEndpoint: elasticsearch
  etlMapping:
    mappings:
      - name: hnc_dataset
        doc_type: dataset
        type: aggregator
        root: dataset
        props:
          - name: project_id
          - name: submitter_id
          - name: data_description
        joining_props:
          - index: data_file
            join_on: _dataset_id
            props:
              - name: object_id
                src: object_id
                fn: set
              - name: data_format
                src: data_format
                fn: set
              - name: data_type
                src: data_type
                fn: set
              - name: data_category
                src: data_category
                fn: set
      - name: hnc_subject
        doc_type: subject
        type: aggregator
        root: subject
        props:
          - name: project_id
          - name: submitter_id
          - name: MRN
          - name: Cancer_Status_Desc
          - name: Cause_of_Death_Desc
          - name: Class_of_Case_Desc
          - name: Date_of_Birth
          - name: Date_of_Last_Contact
          - name: Ethnicity
          - name: Primary_Payer_at_DX_Desc
          - name: Race_1_Desc
          - name: Sex_Desc
          - name: Spanish_Hispanic_Origin_Desc
          - name: Vital_Status_Desc
          - name: date_of_death
          - name: gender
          - name: race
        nested_props:
          - name: sample
            path: sample
            props:
              - name: body_fluid_code
              - name: dna_260_280
              - name: dna_concentration
              - name: dna_od_260
              - name: procedure_date
              - name: protocol_number
              - name: sample_number
              - name: sample_type
              - name: sample_volume
              - name: status
          - name: treatment
            path: treatment
            props:
              - name: Date_of_First_Surgery
              - name: First_Course_Chemotherapy_Date
              - name: First_Course_Chemotherapy_Hosp_Desc
              - name: First_Course_Dx_Staging_Proc_Hosp_Desc
              - name: First_Course_Immunotherapy_Date
              - name: First_Course_Immunotherapy_Hosp_Desc
              - name: Rx_Code_Desc
              - name: Rx_Course_Desc
              - name: Rx_Start_Date
              - name: Rx_Type
              - name: Rx_Type_Desc
              - name: Subseq_Course_Rx_Summary
              - name: Treatment_This_Facility_Desc
          - name: visit
            path: visit
            props:
              - name: ADM_DATE
              - name: CRDW_END_DATE
              - name: CRDW_START_DATE
              - name: DISC_DATE
              - name: dx_name
              - name: dx_rank
              - name: icd10_code
              - name: icd9_code
          - name: diagnosis
            path: diagnosis
            props:
              - name: CS_Mets_at_Dx_Bone_Desc
              - name: CS_Mets_at_Dx_Brain_Desc
              - name: CS_Mets_at_Dx_Liver_Desc
              - name: CS_Mets_at_Dx_Lung_Desc
              - name: CS_Site_Specific_Factor_1
              - name: CS_Site_Specific_Factor_10
              - name: CS_Site_Specific_Factor_2
              - name: CS_Site_Specific_Factor_3
              - name: CS_Site_Specific_Factor_4
              - name: CS_Site_Specific_Factor_5
              - name: CS_Site_Specific_Factor_6
              - name: CS_Site_Specific_Factor_7
              - name: CS_Site_Specific_Factor_8
              - name: CS_Site_Specific_Factor_9
              - name: Clinical_M
              - name: Clinical_N
              - name: Clinical_Stage_Group
              - name: Clinical_T
              - name: Date_of_First_Contact
              - name: Date_of_Initial_Diagnosis
              - name: Laterality
              - name: Mets_at_Dx_Distant_LN
              - name: Mets_at_Dx_Other
              - name: Pathologic_M
              - name: Pathologic_N
              - name: Pathologic_Stage_Descriptor
              - name: Pathologic_Stage_Group
              - name: Pathologic_T
              - name: Primary_Site
              - name: Primary_Site_Desc
              - name: Regional_Nodes_Exam
              - name: Regional_Nodes_Positive
              - name: Site_of_Distant_Metastasis_1_Desc
              - name: Site_of_Distant_Metastasis_2_Desc
              - name: Site_of_Distant_Metastasis_3_Desc
              - name: Size_of_Tumor
              - name: TNM_Edition_Number_Desc
              - name: Tumor_Size_Clinical
              - name: Tumor_Size_Pathological
              - name: Tumor_Size_Summary
        joining_props:
          - index: data_file
            join_on: _subject_id
            props:
              - name: object_id
                src: object_id
                fn: set
              - name: data_format
                src: data_format
                fn: set
              - name: data_type
                src: data_type
                fn: set
              - name: data_category
                src: data_category
                fn: set
      - name: hnc_data_file
        doc_type: data_file
        type: collector
        root: None
        category: data_file
        props:
          - name: source_node
          - name: project_id
          - name: submitter_id
          - name: object_id
          - name: file_name
          - name: data_format
          - name: data_type
          - name: data_category
        injecting_props:
          dataset:
            props:
              - name: _dataset_id
                src: id
                fn: set
          subject:
            props:
              - name: _subject_id
                src: id
                fn: set


fence:
  # Lower cost
  resources:
    requests:
      memory: "105Mi"
      cpu: "15m"
  enabled: true
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::419939494982:role/gen3-service/headneck-default-fence-sa"

  externalSecrets:
    fenceJwtKeys: ""
    fenceConfig: headneck_default-fence-config
    fenceGoogleAppCredsSecret: ""
    fenceGoogleStorageCredsSecret: ""
    createK8sJwtKeysSecret: true
    createK8sGoogleAppSecrets: true
    createK8sFenceConfigSecret: false
    dbcreds: "headneck_default-fence-creds"


  USER_YAML: |
    {}

  usersync:
    usersync: true
    schedule: "*/30 * * * *"
    syncFromDbgap: false
    userYamlS3Path: "s3://cdis-gen3-users/hnc/user.yaml"
    slack_webhook: ""
    slack_send_dbgap: false

frontend-framework:
  # Lower cost
  resources:
    requests:
      memory: "105Mi"
      cpu: "15m"
  enabled: false
  image:
    repository: quay.io/cdis/commons-frontend-app
    tag: main

grafana:
  enabled: false

guppy:
  esEndpoint: elasticsearch:9200
  # Lower cost
  resources:
    requests:
      memory: "105Mi"
      cpu: "15m"
  enabled: true
  indices:
    - index: hnc_dataset
      type: dataset
    - index: hnc_subject
      type: subject
    - index: hnc_data_file
      type: data_file
  configIndex: hnc_array-config


hatchery:
  # Lower cost
  resources:
    requests:
      memory: "105Mi"
      cpu: "15m"
  enabled: true

  hatchery:
    sidecarContainer:
      cpu-limit: '0.1'
      memory-limit: 256Mi
      image: quay.io/cdis/ecs-ws-sidecar:master
      env:
        NAMESPACE: "{{ .Release.Namespace }}"
        HOSTNAME: "{{ .Values.global.hostname }}"
      args: []
      command:
      - "/bin/bash"
      - "./sidecar.sh"
      lifecycle-pre-stop:
      - su
      - "-c"
      - echo test
      - "-s"
      - "/bin/sh"
      - root
    containers:
      -
        target-port: 8888
        cpu-limit: '1.0'
        memory-limit: 2Gi
        name: "(Tutorials) Example Analysis Jupyter Lab Notebooks"
        image: quay.io/cdis/heal-notebooks:combined_tutorials__latest
        env:
          FRAME_ANCESTORS: https://{{ .Values.global.hostname }}
        args:
        - "--NotebookApp.base_url=/lw-workspace/proxy/"
        - "--NotebookApp.default_url=/lab"
        - "--NotebookApp.password=''"
        - "--NotebookApp.token=''"
        - "--NotebookApp.shutdown_no_activity_timeout=5400"
        - "--NotebookApp.quit_button=False"
        command:
        - start-notebook.sh
        path-rewrite: "/lw-workspace/proxy/"
        use-tls: 'false'
        ready-probe: "/lw-workspace/proxy/"
        lifecycle-post-start:
        - "/bin/sh"
        - "-c"
        - export IAM=`whoami`; rm -rf /home/$IAM/pd/dockerHome; rm -rf /home/$IAM/pd/lost+found;
          ln -s /data /home/$IAM/pd/; true
        user-uid: 1000
        fs-gid: 100
        user-volume-location: "/home/jovyan/pd"
        gen3-volume-location: "/home/jovyan/.gen3"


indexd:
  # Lower cost
  resources:
    requests:
      memory: "105Mi"
      cpu: "15m"
  enabled: true
  defaultPrefix: dg.HN3CK/
  externalSecrets:
    dbcreds: "headneck_default-indexd-creds"
    createK8sServiceCredsSecret: true


manifestservice:
  # Lower cost
  resources:
    requests:
      memory: "105Mi"
      cpu: "15m"
  enabled: true
  externalSecrets:
    createK8sManifestServiceSecret: true

metadata:
 # Lower cost
  initResources:
    requests:
      memory: "105Mi"
      cpu: "15m"
  # Lower cost
  resources:
    requests:
      memory: "105Mi"
      cpu: "15m"
  enabled: true
  externalSecrets:
    dbcreds: "headneck_default-metadata-creds"
    createK8sMetadataSecret: true

peregrine:
  # Lower cost
  resources:
    requests:
      memory: "105Mi"
      cpu: "15m"
  enabled: true
  externalSecrets:
    dbcreds: "headneck_default-sheepdog-creds"

pidgin:
  enabled: false

portal:
  replicas: 2
  enabled: true
  image:
    # tag: fix_gqlhelper
    tag: 2025.09
  customConfig:
    enabled: true
    dir: "headneck/headneckcancerbank.data-commons.org/values/portal/"
    repo: https://github.com/uc-cdis/gen3-gitops.git
    branch: master


requestor:
  enabled: false
  externalSecrets:
    dbcreds: "headneck_default-requestor-creds"

revproxy:
  # Lower cost
  resources:
    requests:
      memory: "100Mi"
      cpu: "15m"
  enabled: true

s3-mountpoint:
  enabled: false

sheepdog:
  # Lower cost
  resources:
    requests:
      memory: "105Mi"
      cpu: "15m"
  enabled: true
  externalSecrets:
    dbcreds: "headneck_default-sheepdog-creds"

ssjdispatcher:
  enabled: false

sower:
  enabled: false

wts:
  # Lower cost
  resources:
    requests:
      memory: "105Mi"
      cpu: "15m"
  enabled: true
  externalSecrets:
    dbcreds: "headneck_default-wts-creds"
