cluster: midrcprod
project: midrc

accountNumber: "813684607867"

alb-controller:
  enabled: true
  configuration:
    enabled: false

aws-s3-mountpoint:
  enabled: true
  configuration:
    enabled: true

calico:
  enabled: true
  configuration:
    enabled: false

cert-manager:
  enabled: true

coreDNS:
  enabled: true
  configuration:
    enabled: false

ebs-csi-driver:
  enabled: true
  configuration:
    enabled: false

external-secrets:
  enabled: true

fluentd:
  enabled: false
  configuration:
    enabled: false

kube-state-metrics:
  enabled: true
  configuration:
    enabled: false

grafana-alloy:
  enabled: true
  configuration:
    enabled: false

karpenter:
  enabled: true
  targetRevision: "1.0.8"

karpenter-crds:
  amiSelectorName: "1-31-EKS-FIPS*"
  enabled: true
  selectorTag: midrcprod
  migration: true
  workflow:
    sgSelector: midrcprod
  jupyter:
    requirements:
    - key: karpenter.k8s.aws/instance-cpu
      operator: Lt
      values:
        - "9"
    - key: karpenter.k8s.aws/instance-category
      operator: In
      values:
        - c
    - key: kubernetes.io/arch
      operator: In
      values:
        - amd64
    - key: karpenter.sh/capacity-type
      operator: In
      values:
        - on-demand

vpc-cni:
  enabled: true
  configuration:
    enabled: false
