cluster: kidsfirst-kfqa2
project: kidsfirst

eksClusterName: kfqa2

accountNumber: "222487244010"

eksClusterEndpoint: "https://0390EC57790D396E90741AA0EAA3F54B.sk1.us-east-1.eks.amazonaws.com"

alb-controller:
  enabled: true
  configuration:
    enabled: false

aws-s3-mountpoint:
  enabled: true
  configuration:
    enabled: false

calico:
  enabled: true
  configuration:
    enabled: false

cert-manager:
  enabled: true

coreDNS:
  enabled: true
  configuration:
    enabled: false

ebs-csi-driver:
  enabled: false
  configuration:
    enabled: false

external-secrets:
  enabled: true

fluentd:
  enabled: false
  configuration:
    enabled: false

kube-state-metrics:
  enabled: true
  configuration:
    enabled: false

grafana-alloy:
  enabled: true
  configuration:
    enabled: false

karpenter:
  enabled: true
  targetRevision: "1.0.8"

karpenter-crds:
  amiSelectorName: "1-31-EKS-FIPS*"
  enabled: true
  migration: true
  selectorTag: kfqa2

vpc-cni:
  enabled: true
  configuration:
    enabled: false
