cluster: kidsfirst-kfqa2
project: kidsfirst

grafana-alloy:
  enabled: true
  configuration:
    enabled: false

karpenter-crds:
  amiSelectorName: "1-31-EKS-FIPS*"
  enabled: true
  migration: true
  selectorTag: skfqa
