apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gen3-bihprod
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - path: helm/gen3
      repoURL: https://github.com/uc-cdis/gen3-helm
      targetRevision: feat/deployment-canary
      helm:
        releaseName: gen3-bihprod
        valueFiles:
          - $values/bihprod/imaging-hub.data-commons.org/values/values.yaml
    - repoURL: 'https://github.com/uc-cdis/gen3-gitops.git'
      targetRevision: master
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: bihprod-helm
  syncPolicy:
    syncOptions:
    - CreateNamespace=false
    automated:
      selfHeal: true
