{{ if and (index .Values "karpenter-crds" "enabled") (index .Values "karpenter-crds" "jupyter" "enabled") }}
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: jupyter
spec:
  subnetSelector:
    karpenter.sh/discovery: {{ .Values.cluster }}
  securityGroupSelector:
    karpenter.sh/discovery: {{ .Values.cluster }}-jupyter
  tags:
    Environment: {{ .Values.cluster }}
    Name: eks-{{ .Values.cluster }}-jupyter-karpenter
    karpenter.sh/discovery: {{ .Values.cluster }}
    purpose: jupyter
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: optional
  userData: |
    MIME-Version: 1.0
    Content-Type: multipart/mixed; boundary="BOUNDARY"

    --BOUNDARY
    Content-Type: text/x-shellscript; charset="us-ascii"

    #!/bin/bash -x
    instanceId=$(curl -s http://169.254.169.254/latest/dynamic/instance-identity/document | jq -r .instanceId)
    curl https://raw.githubusercontent.com/uc-cdis/cloud-automation/master/files/authorized_keys/ops_team >> /home/ec2-user/.ssh/authorized_keys

    echo "$(jq '.registryPullQPS=0' /etc/kubernetes/kubelet/kubelet-config.json)" > /etc/kubernetes/kubelet/kubelet-config.json

    sysctl -w fs.inotify.max_user_watches=12000

    # --BOUNDARY
    # Content-Type: text/cloud-config; charset="us-ascii"

    # mounts:
    #   - ['fstype': 'bpf', 'mountpoint': '/sys/fs/bpf', 'opts': 'rw,relatime']

    --BOUNDARY--
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 50Gi
        volumeType: gp2
        encrypted: true
        deleteOnTermination: true
---
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: jupyter
spec:
  # Only allow on demand instance
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["on-demand"]
    - key: kubernetes.io/arch
      operator: In
      values:
      - amd64
    - key: karpenter.k8s.aws/instance-category
      operator: In
      values:
      - c
      - m
      - r
      - t
  # Set a taint for jupyter pods
  taints:
    - key: role
      value: jupyter
      effect: NoSchedule
  labels:
    role: jupyter
  # Set a limit of 1000 vcpus
  limits:
    resources:
      cpu: 1000
  # Use the jupyter node template
  providerRef:
    name: jupyter
  # Allow pods to be rearranged
  consolidation:
    enabled: {{ index .Values "karpenter-crds.jupyter.consolidation" }}
  # Kill nodes after 7 days to ensure they stay up to date
  ttlSecondsUntilExpired: 604800
{{ end }}
