{{ if index .Values "karpenter" "enabled" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: public.ecr.aws/karpenter
      targetRevision: {{ .Values.karpenter.targetRevision }}
      path: karpenter
      helm:
        releaseName: karpenter
      {{- if index .Values "karpenter" "configuration" "enabled" }}
        valueFiles:
          - "$values/{{ .Values.cluster }}/cluster-values/karpenter.yaml"
      skipCrds: true
    - repoURL: {{ .Values.configuration.configurationRepo }}
      targetRevision: {{ .Values.configuration.configurationRevision }}
      ref: values
      {{- else }}
        values: |
          webhook:
            enabled: false
          skipCrds: true
          serviceAccount:
            name: karpenter
            create: true
            annotations:
              eks.amazonaws.com/role-arn: "arn:aws:iam::{{ .Values.accountNumber }}:role/gen3_service/karpenter-controller-role-{{ .Values.eksClusterName | default .Values.cluster }}"
          settings:
            clusterName: {{ .Values.eksClusterName | default .Values.cluster }}
            clusterEndpoint: {{ .Values.eksClusterEndpoint }}
          # controller:
          #   image:
          #     tag: {{ .Values.karpenter.controller.image.tag | default .Values.karpenter.targetRevision }}
          #     digest: {{ .Values.karpenter.controller.image.digest }}
            env:
              - name: AWS_REGION
                value: {{ .Values.karpenter.awsRegion }}
            resources:
              requests:
                memory: {{ .Values.karpenter.resources.requests.memory }}
                cpu: {{ .Values.karpenter.resources.requests.cpu }}
              limits:
                memory: {{ .Values.karpenter.resources.limits.memory }}
                cpu: {{ .Values.karpenter.resources.limits.cpu }}
      {{- end }}
  destination:
    server: "https://kubernetes.default.svc"
    namespace: karpenter
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
{{ end }}
