{{ if index .Values "kube-state-metrics" "enabled" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-state-metrics
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      chart: kube-state-metrics
      targetRevision: {{ index .Values "kube-state-metrics" "targetRevision" }}
      helm:
        releaseName:
      {{- if index .Values "kube-state-metrics" "configuration" "enabled" }}
        valueFiles:
          - "$values/{{ .Values.cluster }}/cluster-values/kube-state-metrics.yaml"
    - repoURL: {{ .Values.configuration.configurationRepo }}
      targetRevision: {{ .Values.configuration.configurationRevision }}
      ref: values
      {{- end }}
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
{{ end }}
