global:
  dev: false
  # uncomment once we cutover, so we can use shared ALB
  #environment: "unfunded"
  hostname: "aids.diseasedatahub.org"
  origins_allow_credentials: ["https://diseasedatahub.org"]
  manifestGlobalExtraValues:
    fence_url: "https://diseasedatahub.org/user"
    arborist_url: "http://arborist-service.diseasedatahub.svc.cluster.local"
    indexd_url: "https://diseasedatahub.org/index/"
    workspace_url: "https://diseasedatahub.org/lw-workspace"
    manifest_service_url: "https://diseasedatahub.org/manifests"
    wts_url: "https://diseasedatahub.org/wts/oauth2/"
    cookie_domain: "diseasedatahub.org"
    des_namespace: "diseasedatahub"
  aws:
    enabled: true
    useLocalSecret:
        enabled: true
        localSecretName: external-secrets-charlie-secret
  revproxyArn: arn:aws:acm:us-east-1:662843554732:certificate/86eca425-c2c3-4911-a49f-20beca8c7e99
  dictionaryUrl: "https://s3.amazonaws.com/dictionary-artifacts/charlie-datadictionary/v1.3.2/schema.json"
  postgres:
    dbCreate: false
    externalSecret: "charlie-master-password"
  externalSecrets:
    # -- (bool) Will use ExternalSecret resources to pull secrets from Secrets Manager instead of creating them locally. Be cautious as this will override secrets you have deployed.
    deploy: true

arborist:
  enabled: true
  externalSecrets:
    dbcreds: "charlie-arborist-db-creds"
  image:
    repository: quay.io/cdis/arborist
    tag: 2023.12

aws-es-proxy:
  esEndpoint: vpc-unfunded-gen3-metadata-2-tf3gyjftzrgm5asaxuvqxxwv2m.us-east-1.es.amazonaws.com
  externalSecrets:
    awsCreds: "charlie-aws-es-proxy-creds"
  enabled: true
  image:
    repository: quay.io/cdis/aws-es-proxy
    tag: v1.3.1

indexd:
  # defaultPrefix: "dg.C78ch/"
  externalSecrets:
    dbcreds: "charlie-indexd-db-creds"
    serviceCreds: "charlie-indexd-service-creds"

  enabled: true
  image:
    repository: quay.io/cdis/indexd
    tag: 2023.12

peregrine:
  externalSecrets:
    dbcreds: "charlie-peregrine-db-creds"
  enabled: true
  image:
    repository: quay.io/cdis/peregrine
    tag: feat_jq-audience
    pullPolicy: Always

revproxy:
  enabled: true
  image:
    repository: quay.io/cdis/nginx
    tag: 2023.12

sheepdog:
  externalSecrets:
    dbcreds: "charlie-sheepdog-db-creds"
  enabled: true
  image:
    repository: quay.io/cdis/sheepdog
    tag: 2023.12

manifestservice:
  enabled: true
  image:
    repository: quay.io/cdis/manifestservice
    tag: 2023.12
  externalSecrets:
    manifestserviceG3auto: "charlie-manifestservice-g3auto"

wts:
  externalSecrets:
    dbcreds: "charlie-wts-db-creds"
  enabled: true
  image:
    repository: quay.io/cdis/workspace-token-service
    tag: 2023.12

# Disabled services
ambassador:
  enabled: false
hatchery:
  enabled: false
audit:
  enabled: false
argo-wrapper:
  enabled: false
pidgin:
  enabled: false
sower:
  enabled: false
ssjdispatcher:
  enabled: false
metadata:
  enabled: false
