global:
  aws:
    enabled: true
    account: "662843554732"
    hatchery_role: "arn:aws:iam::662843554732:role/gen3-service/unfunded-africa-hatchery-sa"
    secretStoreServiceAccount:
      enabled: true
      name: external-secrets
      roleArn: "arn:aws:iam::662843554732:role/gen3_service/unfunded-africa-external-secrets-sa"
    wafv2:
      enabled: true
      wafAclArn: ""
  dev: false
  externalSecrets:
    deploy: true
  postgres:
    dbCreate: true
    externalSecret: "unfunded-aurora-master-password"
  environment: "unfunded"
  hostname: "biocuration.planx-pla.net"
  revproxyArn: "arn:aws:acm:us-east-1:662843554732:certificate/fa13f8ee-5abb-4e0d-89a3-153007d591e0"
  dictionaryUrl: "https://s3.amazonaws.com/dictionary-artifacts/sdc_dictionary/0.0.4/schema.json"
  portalApp: gitops
  publicDataSets: false
  tierAccessLevel: "private"
  tierAccessLimit: "100"
  netPolicy:
    enabled: false
  dispatcherJobNum: "10"
  frontendRoot: "portal"
  ddEnabled: false

ambassador:
  enabled: true

arborist:
  enabled: true
  externalSecrets:
    dbcreds: "unfunded-africa-arborist-creds"

argo-wrapper:
  enabled: false

audit:
  enabled: true
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::662843554732:role/gen3_service/unfunded-africa-audit-sa"
  externalSecrets:
    dbcreds: "unfunded-africa-audit-creds"
    createK8sAuditSecret: true


aws-es-proxy:
  enabled: true
  esEndpoint: "vpc-unfunded-gen3-metadata-2-tf3gyjftzrgm5asaxuvqxxwv2m.us-east-1.es.amazonaws.com"
  externalSecrets:
    awsCreds: "unfunded-africa-aws-es-proxy-creds"

dicom-server:
  enabled: false
  externalSecrets:
    dbcreds: "unfunded-africa-dicom-server-creds"

dicom-viewer:
  enabled: false
  externalSecrets:
    dbcreds: "unfunded-africa-dicom-viewer-creds"


fence:
  enabled: true
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::662843554732:role/gen3_service/unfunded-africa-fence-sa"

  externalSecrets:
    fenceJwtKeys: "unfunded-africa-fence-jwt-keys"
    fenceConfig: "unfunded-africa-fence-config"
    fenceGoogleAppCredsSecret: ""
    fenceGoogleStorageCredsSecret: ""
    createK8sGoogleAppSecrets: true
    dbcreds: "unfunded-africa-fence-creds"

  usersync:
    usersync: true
    schedule: "*/30 * * * *"
    syncFromDbgap: false
    userYamlS3Path: "s3://cdis-gen3-users/dev/user.yaml"
    slack_webhook: ""
    slack_send_dbgap: false

frontend-framework:
  enabled: false
  image:
    repository: "quay.io/cdis/frontend-framework"
    tag: "main"

grafana:
  enabled: false

guppy:
  enabled: false

hatchery:
  enabled: true

  hatchery:
    sidecarContainer:
      cpu-limit: '0.1'
      memory-limit: 256Mi
      image: quay.io/cdis/ecs-ws-sidecar:master
      env:
        NAMESPACE: "{{ .Release.Namespace }}"
        HOSTNAME: "{{ .Values.global.hostname }}"
      args: []
      command:
      - "/bin/bash"
      - "./sidecar.sh"
      lifecycle-pre-stop:
      - su
      - "-c"
      - echo test
      - "-s"
      - "/bin/sh"
      - root
    containers:
      -
        target-port: 8888
        cpu-limit: '1.0'
        memory-limit: 2Gi
        name: "(Tutorials) Example Analysis Jupyter Lab Notebooks"
        image: quay.io/cdis/heal-notebooks:combined_tutorials__latest
        env:
          FRAME_ANCESTORS: https://{{ .Values.global.hostname }}
        args:
        - "--NotebookApp.base_url=/lw-workspace/proxy/"
        - "--NotebookApp.default_url=/lab"
        - "--NotebookApp.password=''" #pragma: allowlist secret
        - "--NotebookApp.token=''"
        - "--NotebookApp.shutdown_no_activity_timeout=5400"
        - "--NotebookApp.quit_button=False"
        command:
        - start-notebook.sh
        path-rewrite: "/lw-workspace/proxy/"
        use-tls: 'false'
        ready-probe: "/lw-workspace/proxy/"
        lifecycle-post-start:
        - "/bin/sh"
        - "-c"
        - export IAM=`whoami`; rm -rf /home/$IAM/pd/dockerHome; rm -rf /home/$IAM/pd/lost+found;
          ln -s /data /home/$IAM/pd/; true
        user-uid: 1000
        fs-gid: 100
        user-volume-location: "/home/jovyan/pd"
        gen3-volume-location: "/home/jovyan/.gen3"


indexd:
  enabled: true
  defaultPrefix: "dg.XXXX/"
  externalSecrets:
    dbcreds: "unfunded-africa-indexd-creds"
    createK8sServiceCredsSecret: true


manifestservice:
  enabled: true
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::662843554732:role/gen3_service/unfunded-africa-manifestservice-sa"
  externalSecrets:
    createK8sManifestServiceSecret: true

metadata:
  enabled: true
  externalSecrets:
    dbcreds: "unfunded-africa-metadata-creds"
    createK8sMetadataSecret: true

peregrine:
  enabled: true
  externalSecrets:
    dbcreds: "unfunded-africa-sheepdog-creds"

pidgin:
  enabled: false

portal:
  enabled: true
  customConfig:
    enabled: true
    dir: unfunded/biocuration.planx-pla.net/portal/
    repo: https://github.com/uc-cdis/gen3-gitops.git
    branch: feat/africa-biocommons


  gitops:
    json: |
      {
        "graphql": {
          "boardCounts": [
            {
              "graphql": "_subject_count",
              "name": "Subject",
              "plural": "Subjects"
            },
            {
              "graphql": "_study_count",
              "name": "Study",
              "plural": "Studies"
            },
            {
              "graphql": "_lab_result_count",
              "name": "Lab Result",
              "plural": "Lab Results"
            }
          ],
          "chartCounts": [
            {
              "graphql": "_subject_count",
              "name": "Subject"
            },
            {
              "graphql": "_study_count",
              "name": "Study"
            },
            {
              "graphql": "_lab_result_count",
              "name": "Lab Result"
            }
          ],
          "projectDetails": "boardCounts"
        },
        "components": {
          "appName": "Sickle Cell Disease Data Commons",
          "index": {
            "introduction": {
              "heading": "Data Commons",
              "text": "The Sickle Cell Data Commons supports the management, analysis and sharing of sickle cell data for the research community.",
              "link": "/submission"
            },
            "buttons": [
              {
                "name": "Define Data Field",
                "icon": "data-field-define",
                "body": "The Gen3 Sickle Cell Data Commons defines the data according to selected properties from the SCDO ontology. Please, study the dictionary before you start browsing.",
                "link": "/DD",
                "label": "Learn more"
              },
              {
                "name": "Explore Data",
                "icon": "data-explore",
                "body": "The Exploration Page facilitates cohort selection using faceted search and offers insights and a clear overview of data.",
                "link": "/explorer",
                "label": "Explore data"
              },
              {
                "name": "Access Data",
                "icon": "data-access",
                "body": "Use our selected tool to filter out the data you need.",
                "link": "/query",
                "label": "Query data"
              },
              {
                "name": "Submit Data",
                "icon": "data-submit",
                "body": "Submit Data based on the dictionary.",
                "link": "/submission",
                "label": "Submit data"
              }
            ]
          },
          "navigation": {
            "title": "Generic Data Commons",
            "items": [
              {
                "icon": "dictionary",
                "link": "/DD",
                "color": "#a2a2a2",
                "name": "Dictionary"
              },
              {
                "icon": "exploration",
                "link": "/explorer",
                "color": "#a2a2a2",
                "name": "Exploration"
              },
              {
                "icon": "query",
                "link": "/query",
                "color": "#a2a2a2",
                "name": "Query"
              },
              {
                "icon": "workspace",
                "link": "/workspace",
                "color": "#a2a2a2",
                "name": "Workspace"
              },
              {
                "icon": "profile",
                "link": "/identity",
                "color": "#a2a2a2",
                "name": "Profile"
              }
            ]
          },
          "topBar": {
            "items": [
              {
                "icon": "upload",
                "link": "/submission",
                "name": "Submit Data"
              },
              {
                "link": "https://docs.gen3.org/gen3-resources/user-guide/",
                "name": "Documentation"
              }
            ]
          },
          "login": {
            "title": "Sickle Cell Disease Data Commons",
            "subTitle": "Explore, Analyze, and Share Data",
            "text": "This website supports the management, analysis and sharing of human disease data for the research community and aims to advance basic understanding of the genetic basis of complex traits and accelerate discovery and development of therapies, diagnostic tests, and other technologies for diseases like cancer.",
            "contact": "If you have any questions about access or the registration process, please contact ",
            "email": "support@gen3.org"
          },
          "certs": {},
          "footerLogos": [
            {
              "src": "/src/img/gen3.png",
              "href": "https://ctds.uchicago.edu/gen3",
              "alt": "Gen3 Data Commons"
            },
            {
              "src": "/src/img/createdby.png",
              "href": "https://ctds.uchicago.edu/",
              "alt": "Center for Translational Data Science at the University of Chicago"
            }
          ]
        },
        "requiredCerts": [],
        "featureFlags": {
          "explorer": true,
          "noIndex": true,
          "analysis": false,
          "discovery": true,
          "discoveryUseAggMDS": false,
          "studyRegistration": false
        },
        "explorerConfig": [
          {
            "tabTitle": "Subjects",
            "charts": {
              "project_id": {
                "chartType": "count",
                "title": "Projects"
              },
              "_subject_id": {
                "chartType": "count",
                "title": "Subjects"
              },
              "gender": {
                "chartType": "pie",
                "title": "Gender"
              },
              "race": {
                "chartType": "bar",
                "title": "Race"
              }
            },
            "filters": {
              "tabs": [
                {
                  "title": "Subject",
                  "fields":[
                    "project_id",
                    "gender",
                    "race",
                    "ethnicity"
                  ]
                }
              ]
            },
            "table": {
              "enabled": false
            },
            "dropdowns": {},
            "buttons": [
              {
              "enabled": true,
              "type": "export-to-workspace",
              "title": "Export to Workspace",
              "leftIcon": "datafile",
              "rightIcon": "download"
              }
              ],
            "guppyConfig": {
              "dataType": "subject",
              "nodeCountTitle": "Subjects",
              "fieldMapping": [
                { "field": "disease_type", "name": "Disease type" },
                { "field": "primary_site", "name": "Site where samples were collected"}
              ],
              "manifestMapping": {
                "resourceIndexType": "file",
                "resourceIdField": "object_id",
                "referenceIdFieldInResourceIndex": "_subject_id",
                "referenceIdFieldInDataIndex": "_subject_id"
              },
              "accessibleFieldCheckList": ["_subject_id"],
              "accessibleValidationField": "_subject_id"
            }
          },
          {
            "tabTitle": "File",
            "charts": {
              "data_type": {
                "chartType": "stackedBar",
                "title": "File Type"
              },
              "data_format": {
                "chartType": "stackedBar",
                "title": "File Format"
              }
            },
            "filters": {
              "tabs": [
                {
                  "title": "File",
                  "fields": [
                    "project_id",
                    "data_type",
                    "data_format"
                  ]
                }
              ]
            },
            "buttons": [
              {
              "enabled": true,
              "type": "export-files-to-workspace",
              "title": "Export to Workspace",
              "leftIcon": "datafile",
              "rightIcon": "download"
              }
            ],
            "table": {
              "enabled": true,
              "fields": [
                "project_id",
                "file_name",
                "file_size",
                "object_id"
              ]
            },
            "dropdowns": {},
            "guppyConfig": {
              "dataType": "file",
              "fieldMapping": [
                { "field": "object_id", "name": "GUID" }
              ],
              "nodeCountTitle": "Files",
              "manifestMapping": {
                "resourceIndexType": "subject",
                "resourceIdField": "_subject_id",
                "referenceIdFieldInResourceIndex": "object_id",
                "referenceIdFieldInDataIndex": "object_id"
              },
              "accessibleFieldCheckList": ["_subject_id"],
              "accessibleValidationField": "_subject_id",
              "downloadAccessor": "object_id"
            }
          }
        ]
      }  

requestor:
  enabled: false
  externalSecrets:
    dbcreds: "unfunded-africa-requestor-creds"

revproxy:
  enabled: true

sheepdog:
  enabled: true
  externalSecrets:
    dbcreds: "unfunded-africa-sheepdog-creds"

ssjdispatcher:
  enabled: false

sower:
  enabled: false

wts:
  enabled: true
  externalSecrets:
    dbcreds: "unfunded-africa-wts-creds"
    createK8sWtsSecret: true
