cluster: brhprod
project: brh

grafana-alloy:
  enabled: true
  configuration:
    enabled: false

karpenter:
  enabled: true

karpenter-crds:
  amiSelectorName: "1-31-EKS-FIPS*"
  enabled: true
  selectorTag: brhprod
  migration: true
