cluster: brhprod
project: brh
accountNumber: "885078588865"

configuration:
  configurationRevision: calico-dev

alb-controller:
  enabled: true
  targetRevision: "1.13.4"
  configuration:
    enabled: true

aws-s3-mountpoint:
  enabled: true
  targetRevision: "2.0.0"
  configuration:
    enabled: false

calico:
  enabled: true
  targetRevision: "3.30.3"
  configuration:
    enabled: false

cert-manager:
  enabled: true
  targetRevision: "1.18.2"

coreDNS:
  enabled: true
  targetRevision: "1.43.1"
  configuration:
    enabled: false

ebs-csi-driver:
  enabled: true
  targetRevision: "1.48.0"
  configuration:
    enabled: false

external-secrets:
  enabled: true

fluentd:
  enabled: false
  configuration:
    enabled: false

kube-state-metrics:
  enabled: true
  targetRevision: "2.16.0"
  configuration:
    enabled: false

grafana-alloy:
  enabled: true
  configuration:
    enabled: false

karpenter:
  enabled: true
  targetRevision: "1.6.3"

karpenter-crds:
  amiSelectorName: "EKS-1-33-al23*"
  enabled: true
  selectorTag: brhprod
  migration: true
  default:
    nodeClassRef:
      apiVersion: karpenter.k8s.aws/v1
      kind: EC2NodeClass
      name: default
    amiFamily: AL2023
    consolidationPolicy: "WhenEmptyOrUnderutilized"
    consolidateAfter: "5m"
    expireAfter: "72h"
    volumeSize: 80Gi
    requirements:
      - key: karpenter.sh/capacity-type
        operator: In
        values:
          - on-demand
          - spot
      - key: kubernetes.io/arch
        operator: In
        values:
          - amd64
      - key: karpenter.k8s.aws/instance-family
        operator: In
        values:
          - r8i-flex
          - m8i-flex
      - key: karpenter.k8s.aws/instance-memory
        operator: Gt
        values:
          - "7000"
  workflow:
    nodeClassRef:
      apiVersion: karpenter.k8s.aws
      kind: EC2NodeClass
      name: workflow
    amiFamily: AL2023
    volumeSize: 80Gi
  jupyter:
    nodeClassRef:
      apiVersion: karpenter.k8s.aws
      kind: EC2NodeClass
      name: jupyter
    amiFamily: AL2023
    volumeSize: 80Gi

vpc-cni:
  enabled: true
  targetRevision: "1.20.1"
  configuration:
    enabled: false
