apiVersion: v2
name: qa-vectis-planx-pla.net
description: qa-vectis-planx-pla.net argo application
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: jeg
    version: "0.1.0"
  - name: workspace-proxy
    version: "0.1.0"
