apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-level-resources
  namespace: argocd
spec:
  project: default
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/uc-cdis/gen3-gitops.git
    targetRevision: master
    path: cluster-level-resources
    helm:
      valueFiles:
        - unfunded/cluster-values/cluster-values.yaml
      releaseName: cluster-level-resources
  syncPolicy:
    automated:
      selfHeal: true
