apiVersion: v2
name: cluster-level-resources
description: An app-of-apps Helm chart that allows for flexible deployment of resources that support Gen3

type: application

version: 0.2.4

appVersion: "1.16.0"
