# The name of the cluster this configuration is going to. This should match the directory name
cluster: unfunded

# This is universal for all of our configuration, we assume that all of the configuration (i.e. values files)
# live in the same repo, on the same branch
configuration:
  configurationRepo: https://github.com/uc-cdis/gen3-gitops
  configurationRevision: master

calico:
  enabled: false
  targetRevision: v3.27.0
  configuration:
    enabled: false

coreDNS:
  enabled: false
  targetRevision: v1.29.0
  configuration:
    enabled: false

karpenter:
  enabled: false
  targetRevision: v0.32.9
  configuration:
    enabled: false

# No enabled flag, because we want this to come up with karpenter at all times
karpenter-templates:
  configuration:
    enabled: false
  targetRevision: feat/karpenter-templates

vpc-cni:
  enabled: false
  targetRevision: v1.16.2
  configuration:
    enabled: false
