global:
  dev: false
  # uncomment once we cutover, so we can use shared ALB
  #environment: "unfunded"
  hostname: "microbiome.diseasedatahub.org"
  origins_allow_credentials: ["https://diseasedatahub.org"]
  manifestGlobalExtraValues:
    fence_url: "https://diseasedatahub.org/user"
    arborist_url: "http://arborist-service.diseasedatahub.svc.cluster.local"
    indexd_url: "https://diseasedatahub.org/index/"
    workspace_url: "https://diseasedatahub.org/lw-workspace"
    manifest_service_url: "https://diseasedatahub.org/manifests"
    wts_url: "https://diseasedatahub.org/wts/oauth2/"
    cookie_domain: "diseasedatahub.org"
    des_namespace: "diseasedatahub"
  aws:
    enabled: true
    useLocalSecret:
        enabled: true
        localSecretName: external-secrets-microbiome-secret
    wafv2:
      # -- (bool) Set to true if using AWS WAFv2
      enabled: true
      # -- (string) ARN for the WAFv2 ACL.
      wafAclArn: arn:aws:wafv2:us-east-1:662843554732:regional/webacl/unfunded-waf/e10ae423-8e4e-48ba-9a0e-52b43f28f6d4
  revproxyArn: arn:aws:acm:us-east-1:662843554732:certificate/86eca425-c2c3-4911-a49f-20beca8c7e99
  dictionaryUrl: "https://dictionary-artifacts.s3.amazonaws.com/microbiome_datadictionary/1.1.1/schema.json"
  postgres:
    dbCreate: false
    externalSecret: "microbiome-master-password"
  externalSecrets:
    # -- (bool) Will use ExternalSecret resources to pull secrets from Secrets Manager instead of creating them locally. Be cautious as this will override secrets you have deployed.
    deploy: true

arborist:
  enabled: true
  externalSecrets:
    dbcreds: "microbiome-arborist-db-creds"
  image:
    repository: quay.io/cdis/arborist
    tag: 2024.09

aws-es-proxy:
  esEndpoint: vpc-unfunded-gen3-metadata-2-tf3gyjftzrgm5asaxuvqxxwv2m.us-east-1.es.amazonaws.com
  externalSecrets:
    awsCreds: "microbiome-aws-es-proxy-creds"
  enabled: true
  image:
    repository: quay.io/cdis/aws-es-proxy
    tag: v1.3.1

indexd:
  # defaultPrefix: "dg.C78ch/"
  externalSecrets:
    dbcreds: "microbiome-indexd-db-creds"
    serviceCreds: "microbiome-indexd-service-creds"

  enabled: true
  image:
    repository: quay.io/cdis/indexd
    tag: 2024.09

peregrine:
  externalSecrets:
    dbcreds: "microbiome-peregrine-db-creds"
  enabled: true
  image:
    repository: quay.io/cdis/peregrine
    tag: 2024.09
    pullPolicy: Always

revproxy:
  enabled: true
  image:
    repository: quay.io/cdis/nginx
    tag: 2024.09

sheepdog:
  externalSecrets:
    dbcreds: "microbiome-sheepdog-db-creds"
  enabled: true
  image:
    repository: quay.io/cdis/sheepdog
    tag: 2024.09

manifestservice:
  enabled: true
  image:
    repository: quay.io/cdis/manifestservice
    tag: 2024.09
  externalSecrets:
    manifestserviceG3auto: "microbiome-manifestservice-g3auto"

wts:
  externalSecrets:
    dbcreds: "microbiome-wts-db-creds"
  enabled: true
  image:
    repository: quay.io/cdis/workspace-token-service
    tag: 2024.09

# Disabled services
ambassador:
  enabled: false
hatchery:
  enabled: false
audit:
  enabled: false
argo-wrapper:
  enabled: false
pidgin:
  enabled: false
sower:
  enabled: false
ssjdispatcher:
  enabled: false
metadata:
  enabled: false
