global:
  dev: false
  hostname: gen3.datacommons.io
  aws:
    enabled: true
    awsEsProxyRoleArn: arn:aws:iam::662843554732:role/unfunded-elasticsearch-access-role
    useLocalSecret:
      enabled: true
      localSecretName: external-secrets-oadc-secret
    wafv2:
      enabled: true
      wafAclArn: arn:aws:wafv2:us-east-1:662843554732:regional/webacl/unfunded-waf/e10ae423-8e4e-48ba-9a0e-52b43f28f6d4
  revproxyArn: arn:aws:acm:us-east-1:662843554732:certificate/42215b51-29cc-47de-b189-c51bb2e07d97
  dictionaryUrl: http://s3.amazonaws.com/dictionary-artifacts/openaccess_dictionary/0.3.0/schema.json
  postgres:
    dbCreate: false
    externalSecret: pg-master
  externalSecrets:
    deploy: true
  pdb: true
arborist:
  resources:
    requests:
      memory: 105Mi
      cpu: 15m
  enabled: true
  externalSecrets:
    dbcreds: oadc-arborist-db-creds
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/arborist
    tag: '2025.09'
aws-es-proxy:
  resources:
    requests:
      memory: 105Mi
      cpu: 15m
  esEndpoint: vpc-unfunded-gen3-metadata-2-tf3gyjftzrgm5asaxuvqxxwv2m.us-east-1.es.amazonaws.com
  externalSecrets:
    awsCreds: oadc-aws-es-proxy-creds
  enabled: true
indexd:
  resources:
    requests:
      memory: 105Mi
      cpu: 15m
  defaultPrefix: dg.C78ne/
  externalSecrets:
    dbcreds: oadc-indexd-db-creds
    serviceCreds: oadc-indexd-service-creds
  enabled: true
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/indexd
    tag: '2025.09'
peregrine:
  resources:
    requests:
      memory: 105Mi
      cpu: 15m
  externalSecrets:
    dbcreds: oadc-peregrine-db-creds
  enabled: true
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/peregrine
    tag: '2025.09'
    pullPolicy: Always
revproxy:
  resources:
    requests:
      memory: 105Mi
      cpu: 15m
  enabled: true
  replicaCount: 2
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/nginx
    tag: '2025.09'
sheepdog:
  resources:
    requests:
      memory: 105Mi
      cpu: 15m
  externalSecrets:
    dbcreds: oadc-sheepdog-db-creds
  enabled: true
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/sheepdog
    tag: '2025.09'
manifestservice:
  resources:
    requests:
      memory: 105Mi
      cpu: 15m
  enabled: true
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/manifestservice
    tag: '2025.09'
  externalSecrets:
    manifestserviceG3auto: oadc-manifestservice-g3auto
sower:
  resources:
    requests:
      memory: 105Mi
      cpu: 15m
  enabled: true
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/sower
    tag: '2025.09'
  externalSecrets:
    pelicanserviceG3auto: oadc-pelicanservice-g3auto
ssjdispatcher:
  resources:
    requests:
      memory: 105Mi
      cpu: 15m
  enabled: true
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/ssjdispatcher
    tag: '2025.09'
  externalSecrets:
    createK8sSsjdispatcherSecret: true
  indexing: quay.io/cdis/indexs3client:2025.09
metadata:
  resources:
    requests:
      memory: 105Mi
      cpu: 15m
  externalSecrets:
    dbcreds: oadc-metadata-db-creds
    metadataG3auto: oadc-metadata-g3auto
  enabled: true
  esEndpoint: http://elasticsearch:9200
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/metadata-service
    tag: '2025.09'
ambassador:
  enabled: false
wts:
  enabled: false
hatchery:
  enabled: false
audit:
  enabled: false
pidgin:
  enabled: false
