global:
  dev: false
  # uncomment once we cutover, so we can use shared ALB
  #environment: "unfunded"
  hostname: "gen3.datacommons.io"
  aws:
    enabled: true
    useLocalSecret:
      enabled: true
      localSecretName: external-secrets-oadc-secret # pragma: allowlist secret
    wafv2:
      # -- (bool) Set to true if using AWS WAFv2
      enabled: true
      # -- (string) ARN for the WAFv2 ACL.
      wafAclArn: arn:aws:wafv2:us-east-1:662843554732:regional/webacl/unfunded-waf/e10ae423-8e4e-48ba-9a0e-52b43f28f6d4
    secretStoreServiceAccount:
      enabled: true
      roleArn: arn:aws:iam::662843554732:role/unfunded--oadchelm--external-secrets-sa
  revproxyArn: arn:aws:acm:us-east-1:662843554732:certificate/42215b51-29cc-47de-b189-c51bb2e07d97
  dictionaryUrl: "http://s3.amazonaws.com/dictionary-artifacts/openaccess_dictionary/0.3.0/schema.json"
  postgres:
    dbCreate: false
    externalSecret: "pg-master" # pragma: allowlist secret
  externalSecrets:
    # -- (bool) Will use ExternalSecret resources to pull secrets from Secrets Manager instead of creating them locally. Be cautious as this will override secrets you have deployed.
    deploy: true
  pdb: true

arborist:
  # Lower cost
  resources:
    requests:
      memory: "105Mi"
      cpu: "15m"
  enabled: true
  externalSecrets:
    dbcreds: "oadc-arborist-db-creds"
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/arborist
    tag: 2024.09

aws-es-proxy:
  # Lower cost
  resources:
    requests:
      memory: "105Mi"
      cpu: "15m"
  esEndpoint: vpc-unfunded-gen3-metadata-2-tf3gyjftzrgm5asaxuvqxxwv2m.us-east-1.es.amazonaws.com
  externalSecrets:
    awsCreds: "oadc-aws-es-proxy-creds"
  enabled: true
  image:
    repository: quay.io/cdis/aws-es-proxy
    tag: 0.8

indexd:
  # Lower cost
  resources:
    requests:
      memory: "105Mi"
      cpu: "15m"
  defaultPrefix: "dg.C78ne/"

  externalSecrets:
    dbcreds: "oadc-indexd-db-creds"
    serviceCreds: "oadc-indexd-service-creds"

  enabled: true
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/indexd
    tag: 2024.09

peregrine:
  # Lower cost
  resources:
    requests:
      memory: "105Mi"
      cpu: "15m"
  externalSecrets:
    dbcreds: "oadc-peregrine-db-creds"
  enabled: true
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/peregrine
    tag: feat_jq-audience
    pullPolicy: Always

revproxy:
  # Lower cost
  resources:
    requests:
      memory: "105Mi"
      cpu: "15m"
  enabled: true
  replicaCount: 2
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/nginx
    tag: 2024.09

sheepdog:
  # Lower cost
  resources:
    requests:
      memory: "105Mi"
      cpu: "15m"
  externalSecrets:
    dbcreds: "oadc-sheepdog-db-creds"
  enabled: true
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/sheepdog
    tag: 2024.09

manifestservice:
  # Lower cost
  resources:
    requests:
      memory: "105Mi"
      cpu: "15m"
  enabled: true
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/manifestservice
    tag: 2024.09
  externalSecrets:
    manifestserviceG3auto: "oadc-manifestservice-g3auto"

sower:
  # Lower cost
  resources:
    requests:
      memory: "105Mi"
      cpu: "15m"
  enabled: true
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/sower
    tag: 2024.09
  externalSecrets:
    pelicanserviceG3auto: "oadc-pelicanservice-g3auto"

ssjdispatcher:
  # Lower cost
  resources:
    requests:
      memory: "105Mi"
      cpu: "15m"
  enabled: true
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/ssjdispatcher
    tag: 2024.09

metadata:
  # Lower cost
  resources:
    requests:
      memory: "105Mi"
      cpu: "15m"
  externalSecrets:
    dbcreds: "oadc-metadata-db-creds"
    metadataG3auto: "oadc-metadata-g3auto"
  enabled: true
  esEndpoint: http://elasticsearch:9200
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/metadata-service
    tag: 2024.09

# disabling workspace services
ambassador:
  enabled: false
wts:
  enabled: false
hatchery:
  enabled: false

# Disabled services
audit:
  enabled: false
pidgin:
  enabled: false
